package com.jiguro.bettervia;
import android.content.Context;
import android.os.Build;
import java.util.Locale;
import java.util.HashMap;
import java.util.Map;
public class LocalizedStringProvider {
	private static LocalizedStringProvider instance;
	private Map<String, Map<String, String>> localizedStrings;
	private LocalizedStringProvider() {
		initializeLocalizedStrings();
	}
	public static LocalizedStringProvider getInstance() {
		if (instance == null) {
			instance = new LocalizedStringProvider();
		}
		return instance;
	}
	private void initializeLocalizedStrings() {
		localizedStrings = new HashMap<>();
		addLocalizedString("module_settings", "zh-CN", "模块");
		addLocalizedString("module_settings", "zh-TW", "模組");
		addLocalizedString("module_settings", "en", "Module");
		addLocalizedString("dialog_ok", "zh-CN", "确定");
		addLocalizedString("dialog_ok", "zh-TW", "确定");
		addLocalizedString("dialog_ok", "en", "OK");
		addLocalizedString("dialog_cancel", "zh-CN", "取消");
		addLocalizedString("dialog_cancel", "zh-TW", "取消");
		addLocalizedString("dialog_cancel", "en", "Cancel");
		addLocalizedString("dialog_back", "zh-CN", "返回");
		addLocalizedString("dialog_back", "zh-TW", "返回");
		addLocalizedString("dialog_back", "en", "Back");
		addLocalizedString("dialog_close", "zh-CN", "关闭");
		addLocalizedString("dialog_close", "zh-TW", "關閉");
		addLocalizedString("dialog_close", "en", "Close");
		addLocalizedString("language_title", "zh-CN", "语言设置");
		addLocalizedString("language_title", "zh-TW", "语言设置");
		addLocalizedString("language_title", "en", "Language");
		addLocalizedString("language_hint", "zh-CN", "设置模块界面和功能提示的语言");
		addLocalizedString("language_hint", "zh-TW", "設置模組界面和功能提示的語言");
		addLocalizedString("language_hint", "en", "Set the language for module interface and feature hints");
		addLocalizedString("language_auto", "zh-CN", "自动选择语言");
		addLocalizedString("language_auto", "zh-TW", "自动选择语言");
		addLocalizedString("language_auto", "en", "Auto Select Language");
		addLocalizedString("language_zh_cn", "zh-CN", "简体中文");
		addLocalizedString("language_zh_cn", "zh-TW", "简体中文");
		addLocalizedString("language_zh_cn", "en", "Simplified Chinese");
		addLocalizedString("language_zh_tw", "zh-CN", "繁體中文");
		addLocalizedString("language_zh_tw", "zh-TW", "繁體中文");
		addLocalizedString("language_zh_tw", "en", "Traditional Chinese");
		addLocalizedString("language_en", "zh-CN", "English");
		addLocalizedString("language_en", "zh-TW", "English");
		addLocalizedString("language_en", "en", "English");
		addLocalizedString("toast_language_auto", "zh-CN", "已设置为自动选择语言");
		addLocalizedString("toast_language_auto", "zh-TW", "已设置为自动选择语言");
		addLocalizedString("toast_language_auto", "en", "Set to auto select language");
		addLocalizedString("toast_language_zh_cn", "zh-CN", "已设置为简体中文");
		addLocalizedString("toast_language_zh_cn", "zh-TW", "已设置为简体中文");
		addLocalizedString("toast_language_zh_cn", "en", "Set to Simplified Chinese");
		addLocalizedString("toast_language_zh_tw", "zh-CN", "已設置為繁體中文");
		addLocalizedString("toast_language_zh_tw", "zh-TW", "已設置為繁體中文");
		addLocalizedString("toast_language_zh_tw", "en", "Set to Traditional Chinese");
		addLocalizedString("toast_language_en", "zh-CN", "Set to English");
		addLocalizedString("toast_language_en", "zh-TW", "Set to English");
		addLocalizedString("toast_language_en", "en", "Set to English");
		addLocalizedString("whitelist_switch", "zh-CN", "解除白名单限制");
		addLocalizedString("whitelist_switch", "zh-TW", "解除白名單限制");
		addLocalizedString("whitelist_switch", "en", "Bypass Whitelist");
		addLocalizedString("whitelist_hint", "zh-CN", "解除某些网站的资源嗅探、广告拦截和脚本限制");
		addLocalizedString("whitelist_hint", "zh-TW", "解除某些網站的資源嗅探、廣告攔截和腳本限制");
		addLocalizedString("whitelist_hint", "en",
				"Unblock resource sniffing, ad blocking and script restrictions for certain websites");
		addLocalizedString("hook_success_message", "zh-CN", "領域展開，りょういきてんかい !");
		addLocalizedString("hook_success_message", "zh-TW", "領域展開，りょういきてんかい !");
		addLocalizedString("hook_success_message", "en", "Field Expansion，りょういきてんかい !");
		addLocalizedString("component_block_title", "zh-CN", "屏蔽组件");
		addLocalizedString("component_block_title", "zh-TW", "屏蔽組件");
		addLocalizedString("component_block_title", "en", "Block Components");
		addLocalizedString("component_block_config", "zh-CN", "配置");
		addLocalizedString("component_block_config", "zh-TW", "配置");
		addLocalizedString("component_block_config", "en", "Configure");
		addLocalizedString("component_block_hint", "zh-CN", "点击配置要屏蔽的组件");
		addLocalizedString("component_block_hint", "zh-TW", "點擊配置要屏蔽的組件");
		addLocalizedString("component_block_hint", "en", "Click to configure components to block");
		addLocalizedString("component_block_dialog_title", "zh-CN", "选择要屏蔽的组件");
		addLocalizedString("component_block_dialog_title", "zh-TW", "選擇要屏蔽的組件");
		addLocalizedString("component_block_dialog_title", "en", "Select Components to Block");
		addLocalizedString("component_block_saved", "zh-CN", "设置已保存");
		addLocalizedString("component_block_saved", "zh-TW", "設置已保存");
		addLocalizedString("component_block_saved", "en", "Settings saved");
		addLocalizedString("component_update", "zh-CN", "检查更新");
		addLocalizedString("component_update", "zh-TW", "检查更新");
		addLocalizedString("component_update", "en", "检查更新");
		addLocalizedString("component_telegram", "zh-CN", "加入 Telegram 群组");
		addLocalizedString("component_telegram", "zh-TW", "加入 Telegram 群组");
		addLocalizedString("component_telegram", "en", "加入 Telegram 群组");
		addLocalizedString("component_qq", "zh-CN", "加入 QQ 群组");
		addLocalizedString("component_qq", "zh-TW", "加入 QQ 群组");
		addLocalizedString("component_qq", "en", "加入 QQ 群组");
		addLocalizedString("component_email", "zh-CN", "通过邮件联系我");
		addLocalizedString("component_email", "zh-TW", "通过邮件联系我");
		addLocalizedString("component_email", "en", "通过邮件联系我");
		addLocalizedString("component_wechat", "zh-CN", "微信公众号");
		addLocalizedString("component_wechat", "zh-TW", "微信公众号");
		addLocalizedString("component_wechat", "en", "微信公众号");
		addLocalizedString("component_donate", "zh-CN", "捐助我们");
		addLocalizedString("component_donate", "zh-TW", "捐助我们");
		addLocalizedString("component_donate", "en", "捐助我们");
		addLocalizedString("component_assist", "zh-CN", "协助翻译");
		addLocalizedString("component_assist", "zh-TW", "协助翻译");
		addLocalizedString("component_assist", "en", "协助翻译");
		addLocalizedString("component_agreement", "zh-CN", "使用协议");
		addLocalizedString("component_agreement", "zh-TW", "使用协议");
		addLocalizedString("component_agreement", "en", "使用协议");
		addLocalizedString("component_privacy", "zh-CN", "隐私政策");
		addLocalizedString("component_privacy", "zh-TW", "隐私政策");
		addLocalizedString("component_privacy", "en", "隐私政策");
		addLocalizedString("component_opensource", "zh-CN", "开源许可协议");
		addLocalizedString("component_opensource", "zh-TW", "开源许可协议");
		addLocalizedString("component_opensource", "en", "开源许可协议");
		addLocalizedString("component_icp", "zh-CN", "备案号");
		addLocalizedString("component_icp", "zh-TW", "备案号");
		addLocalizedString("component_icp", "en", "备案号");
		addLocalizedString("eye_protection_switch", "zh-CN", "护眼模式");
		addLocalizedString("eye_protection_switch", "zh-TW", "護眼模式");
		addLocalizedString("eye_protection_switch", "en", "Eye Protection Mode");
		addLocalizedString("eye_protection_hint", "zh-CN", "屏幕偏暖，减少蓝光对眼睛的伤害");
		addLocalizedString("eye_protection_hint", "zh-TW", "屏幕偏暖，減少藍光對眼睛的傷害");
		addLocalizedString("eye_protection_hint", "en",
				"The screen is warmer to reduce the damage of blue light to the eyes");
		addLocalizedString("eye_protection_config", "zh-CN", "护眼调节");
		addLocalizedString("eye_protection_config", "zh-TW", "護眼調節");
		addLocalizedString("eye_protection_config", "en", "Eye Protection Adjust");
		addLocalizedString("eye_protection_config_btn", "zh-CN", "配置");
		addLocalizedString("eye_protection_config_btn", "zh-TW", "配置");
		addLocalizedString("eye_protection_config_btn", "en", "Configure");
		addLocalizedString("eye_protection_config_hint", "zh-CN", "点击调节色温和纸质纹理");
		addLocalizedString("eye_protection_config_hint", "zh-TW", "點擊調節色溫和紙質紋理");
		addLocalizedString("eye_protection_config_hint", "en", "Click to adjust temperature and paper texture");
		addLocalizedString("eye_protection_config_dialog_title", "zh-CN", "护眼调节");
		addLocalizedString("eye_protection_config_dialog_title", "zh-TW", "護眼調節");
		addLocalizedString("eye_protection_config_dialog_title", "en", "Eye Protection Adjust");
		addLocalizedString("eye_protection_config_subtitle", "zh-CN", "护眼模式设置");
		addLocalizedString("eye_protection_config_subtitle", "zh-TW", "護眼模式設置");
		addLocalizedString("eye_protection_config_subtitle", "en", "Eye Protection Settings");
		addLocalizedString("eye_protection_temperature", "zh-CN", "色温调节");
		addLocalizedString("eye_protection_temperature", "zh-TW", "色溫調節");
		addLocalizedString("eye_protection_temperature", "en", "Color Temperature");
		addLocalizedString("eye_protection_texture", "zh-CN", "纸质纹理");
		addLocalizedString("eye_protection_texture", "zh-TW", "紙質紋理");
		addLocalizedString("eye_protection_texture", "en", "Paper Texture");
		addLocalizedString("eye_protection_cold", "zh-CN", "偏冷");
		addLocalizedString("eye_protection_cold", "zh-TW", "偏冷");
		addLocalizedString("eye_protection_cold", "en", "Cool");
		addLocalizedString("eye_protection_warm", "zh-CN", "偏暖");
		addLocalizedString("eye_protection_warm", "zh-TW", "偏暖");
		addLocalizedString("eye_protection_warm", "en", "Warm");
		addLocalizedString("eye_protection_smooth", "zh-CN", "光滑");
		addLocalizedString("eye_protection_smooth", "zh-TW", "光滑");
		addLocalizedString("eye_protection_smooth", "en", "Smooth");
		addLocalizedString("eye_protection_rough", "zh-CN", "粗糙");
		addLocalizedString("eye_protection_rough", "zh-TW", "粗糙");
		addLocalizedString("eye_protection_rough", "en", "Rough");
		addLocalizedString("eye_protection_preview_title", "zh-CN", "效果预览");
		addLocalizedString("eye_protection_preview_title", "zh-TW", "效果預覽");
		addLocalizedString("eye_protection_preview_title", "en", "Preview");
		addLocalizedString("eye_protection_sample_text", "zh-CN", "片云天共远，永夜月同孤。");
		addLocalizedString("eye_protection_sample_text", "zh-TW", "片雲天共遠，永夜月同孤。");
		addLocalizedString("eye_protection_sample_text", "en", "This is sample text");
		addLocalizedString("eye_protection_preview_hint", "zh-CN", "开启护眼模式后可实时预览效果");
		addLocalizedString("eye_protection_preview_hint", "zh-TW", "開啟護眼模式後可實時預覽效果");
		addLocalizedString("eye_protection_preview_hint", "en",
				"Real-time preview available when eye protection is enabled");
		addLocalizedString("eye_protection_config_saved", "zh-CN", "护眼设置已保存");
		addLocalizedString("eye_protection_config_saved", "zh-TW", "護眼設置已保存");
		addLocalizedString("eye_protection_config_saved", "en", "Eye protection settings saved");
		addLocalizedString("block_google_switch", "zh-CN", "超级隐身");
		addLocalizedString("block_google_switch", "zh-TW", "超級隱身");
		addLocalizedString("block_google_switch", "en", "Super Stealth");
		addLocalizedString("block_google_hint", "zh-CN", "阻止收集用户隐私数据，增强安全性");
		addLocalizedString("block_google_hint", "zh-TW", "阻止收集用戶隱私數據，增強安全性");
		addLocalizedString("block_google_hint", "en",
				"Prevent the collection of user private data and enhance security");
		addLocalizedString("block_startup_message_switch", "zh-CN", "屏蔽启动提示");
		addLocalizedString("block_startup_message_switch", "zh-TW", "屏蔽啟動提示");
		addLocalizedString("block_startup_message_switch", "en", "Block Startup Message");
		addLocalizedString("block_startup_message_hint", "zh-CN", "启动时不显示领域展开提示");
		addLocalizedString("block_startup_message_hint", "zh-TW", "啟動時不顯示領域展開提示");
		addLocalizedString("block_startup_message_hint", "en", "Don't show the field expansion message on startup");
		addLocalizedString("screenshot_protection_switch", "zh-CN", "截屏防护");
		addLocalizedString("screenshot_protection_switch", "zh-TW", "截屏防護");
		addLocalizedString("screenshot_protection_switch", "en", "Screenshot Protection");
		addLocalizedString("screenshot_protection_hint", "zh-CN", "禁止第三方应用截屏或录屏，保护隐私");
		addLocalizedString("screenshot_protection_hint", "zh-TW", "禁止第三方應用截屏或錄屏，保護隱私");
		addLocalizedString("screenshot_protection_hint", "en",
				"Prevent third-party apps from taking screenshots or recording screen to protect privacy");
		addLocalizedString("keep_screen_on_switch", "zh-CN", "屏幕常亮");
		addLocalizedString("keep_screen_on_switch", "zh-TW", "屏幕常亮");
		addLocalizedString("keep_screen_on_switch", "en", "Keep Screen On");
		addLocalizedString("keep_screen_on_hint", "zh-CN", "防止屏幕自动息屏，但会增加耗电");
		addLocalizedString("keep_screen_on_hint", "zh-TW", "防止屏幕自動息屏，但會增加耗電");
		addLocalizedString("keep_screen_on_hint", "en",
				"Prevent screen from turning off automatically, but will increase battery consumption");
		addLocalizedString("background_video_switch", "zh-CN", "后台听视频");
		addLocalizedString("background_video_switch", "zh-TW", "後台聽影片");
		addLocalizedString("background_video_switch", "en", "Background Video Audio");
		addLocalizedString("background_video_hint", "zh-CN", "在浏览器播放视频时置于后台，声音不会停止");
		addLocalizedString("background_video_hint", "zh-TW", "在瀏覽器播放影片時置於後台，聲音不會停止");
		addLocalizedString("background_video_hint", "en", "Continue playing audio when video is in background");
		addLocalizedString("hide_status_bar_switch", "zh-CN", "隐藏状态栏");
		addLocalizedString("hide_status_bar_switch", "zh-TW", "隱藏狀態欄");
		addLocalizedString("hide_status_bar_switch", "en", "Hide Status Bar");
		addLocalizedString("hide_status_bar_hint", "zh-CN", "隐藏屏幕上方的状态栏，下滑即可恢复");
		addLocalizedString("hide_status_bar_hint", "zh-TW", "隱藏屏幕上方的狀態欄，下滑即可恢復");
		addLocalizedString("hide_status_bar_hint", "en",
				"Hide the status bar at the top of the screen and slide it down to restore it");
		addLocalizedString("block_swipe_back_switch", "zh-CN", "屏蔽右滑返回");
		addLocalizedString("block_swipe_back_switch", "zh-TW", "屏蔽右滑返回");
		addLocalizedString("block_swipe_back_switch", "en", "Block Swipe Back");
		addLocalizedString("block_swipe_back_hint", "zh-CN", "禁用右滑返回手势，防止误触返回，网页内容仍可滑动");
		addLocalizedString("block_swipe_back_hint", "zh-TW", "禁用右滑返回手勢，防止誤觸返回，網頁內容仍可滑動");
		addLocalizedString("block_swipe_back_hint", "en",
				"Disable swipe back gesture to prevent accidental back, page content still scrollable");
		addLocalizedString("search_commands_title", "zh-CN", "搜索指令");
		addLocalizedString("search_commands_title", "zh-TW", "搜尋指令");
		addLocalizedString("search_commands_title", "en", "Search Commands");
		addLocalizedString("search_commands_config", "zh-CN", "查看");
		addLocalizedString("search_commands_config", "zh-TW", "查看");
		addLocalizedString("search_commands_config", "en", "View");
		addLocalizedString("search_commands_hint", "zh-CN", "查看所有Via搜索指令");
		addLocalizedString("search_commands_hint", "zh-TW", "查看所有Via搜尋指令");
		addLocalizedString("search_commands_hint", "en", "View all Via search commands");
		addLocalizedString("search_commands_dialog_title", "zh-CN", "Via搜索指令大全");
		addLocalizedString("search_commands_dialog_title", "zh-TW", "Via搜尋指令大全");
		addLocalizedString("search_commands_dialog_title", "en", "Via Search Commands");
		addLocalizedString("search_commands_subtitle", "zh-CN", "以下指令可在Via浏览器地址栏中使用");
		addLocalizedString("search_commands_subtitle", "zh-TW", "以下指令可在Via瀏覽器地址欄中使用");
		addLocalizedString("search_commands_subtitle", "en",
				"The following commands can be used in Via browser address bar");
		addLocalizedString("command_copy", "zh-CN", "复制");
		addLocalizedString("command_copy", "zh-TW", "复制");
		addLocalizedString("command_copy", "en", "Copy");
		addLocalizedString("command_copied", "zh-CN", "已复制到剪贴板");
		addLocalizedString("command_copied", "zh-TW", "已複製到剪貼簿");
		addLocalizedString("command_copied", "en", "Copied to clipboard");
		addLocalizedString("command_bookmark", "zh-CN", "打开书签");
		addLocalizedString("command_bookmark", "zh-TW", "開啟書籤籤");
		addLocalizedString("command_bookmark", "en", "Open bookmarks");
		addLocalizedString("command_search", "zh-CN", "打开搜索框");
		addLocalizedString("command_search", "zh-TW", "開啟搜尋框");
		addLocalizedString("command_search", "en", "Open search box");
		addLocalizedString("command_unknown", "zh-CN", "功能未知");
		addLocalizedString("command_unknown", "zh-TW", "功能未知");
		addLocalizedString("command_unknown", "en", "Unknown function");
		addLocalizedString("command_print", "zh-CN", "打印当前网页");
		addLocalizedString("command_print", "zh-TW", "列印當前網頁");
		addLocalizedString("command_print", "en", "Print current page");
		addLocalizedString("command_adblock", "zh-CN", "拦截广告");
		addLocalizedString("command_adblock", "zh-TW", "攔截廣告");
		addLocalizedString("command_adblock", "en", "Block ads");
		addLocalizedString("command_log", "zh-CN", "打开日志");
		addLocalizedString("command_log", "zh-TW", "開啟日誌");
		addLocalizedString("command_log", "en", "Open logs");
		addLocalizedString("command_home", "zh-CN", "打开主页");
		addLocalizedString("command_home", "zh-TW", "開啟主頁");
		addLocalizedString("command_home", "en", "Open home page");
		addLocalizedString("command_skins", "zh-CN", "打开皮肤");
		addLocalizedString("command_skins", "zh-TW", "開啟皮膚");
		addLocalizedString("command_skins", "en", "Open skins");
		addLocalizedString("command_about", "zh-CN", "打开关于");
		addLocalizedString("command_about", "zh-TW", "開啟關於");
		addLocalizedString("command_about", "en", "Open about");
		addLocalizedString("command_search_page", "zh-CN", "打开搜索页面");
		addLocalizedString("command_search_page", "zh-TW", "開啟搜尋頁面");
		addLocalizedString("command_search_page", "en", "Open search page");
		addLocalizedString("command_offline", "zh-CN", "打开离线窗口");
		addLocalizedString("command_offline", "zh-TW", "開啟離線視窗");
		addLocalizedString("command_offline", "en", "Open offline window");
		addLocalizedString("command_history", "zh-CN", "打开历史");
		addLocalizedString("command_history", "zh-TW", "開啟歷史");
		addLocalizedString("command_history", "en", "Open history");
		addLocalizedString("command_scanner", "zh-CN", "扫二维码");
		addLocalizedString("command_scanner", "zh-TW", "掃描QR碼");
		addLocalizedString("command_scanner", "en", "Scan QR code");
		addLocalizedString("command_bookmarks_page", "zh-CN", "打开书签页面");
		addLocalizedString("command_bookmarks_page", "zh-TW", "開啟書籤籤頁面");
		addLocalizedString("command_bookmarks_page", "en", "Open bookmarks page");
		addLocalizedString("command_downloader", "zh-CN", "打开下载管理");
		addLocalizedString("command_downloader", "zh-TW", "開啟下載管理");
		addLocalizedString("command_downloader", "en", "Open download manager");
		addLocalizedString("command_readaloud", "zh-CN", "阅读控制器");
		addLocalizedString("command_readaloud", "zh-TW", "閱讀控制器");
		addLocalizedString("command_readaloud", "en", "Reading controller");
		addLocalizedString("command_translator", "zh-CN", "翻译文本");
		addLocalizedString("command_translator", "zh-TW", "翻譯文字");
		addLocalizedString("command_translator", "en", "Translate text");
		addLocalizedString("command_history_page", "zh-CN", "打开历史页面");
		addLocalizedString("command_history_page", "zh-TW", "開啟歷史頁面");
		addLocalizedString("command_history_page", "en", "Open history page");
		addLocalizedString("command_folder", "zh-CN", "打开书签文件夹");
		addLocalizedString("command_folder", "zh-TW", "開啟書籤籤資料夾");
		addLocalizedString("command_folder", "en", "Open bookmarks folder");
		addLocalizedString("homepage_theme_title", "zh-CN", "主页主题");
		addLocalizedString("homepage_theme_title", "zh-TW", "主頁主題");
		addLocalizedString("homepage_theme_title", "en", "Homepage Theme");
		addLocalizedString("homepage_theme_config", "zh-CN", "配置");
		addLocalizedString("homepage_theme_config", "zh-TW", "配置");
		addLocalizedString("homepage_theme_config", "en", "Configure");
		addLocalizedString("homepage_theme_hint", "zh-CN", "自定义Via浏览器主页外观");
		addLocalizedString("homepage_theme_hint", "zh-TW", "自定義Via瀏覽器主頁外觀");
		addLocalizedString("homepage_theme_hint", "en", "Customize Via browser homepage appearance");
		addLocalizedString("homepage_theme_dialog_title", "zh-CN", "主页主题");
		addLocalizedString("homepage_theme_dialog_title", "zh-TW", "主頁主題");
		addLocalizedString("homepage_theme_dialog_title", "en", "Homepage Themes");
		addLocalizedString("homepage_theme_subtitle", "zh-CN", "丰富的主题资源");
		addLocalizedString("homepage_theme_subtitle", "zh-TW", "豐富的主題資源");
		addLocalizedString("homepage_theme_subtitle", "en", "Rich theme resources");
		addLocalizedString("homepage_theme_by", "zh-CN", "作者：");
		addLocalizedString("homepage_theme_by", "zh-TW", "作者：");
		addLocalizedString("homepage_theme_by", "en", "By ");
		addLocalizedString("homepage_theme_developing", "zh-CN", "正在开发中...");
		addLocalizedString("homepage_theme_developing", "zh-TW", "正在開發中...");
		addLocalizedString("homepage_theme_developing", "en", "Developing...");
		addLocalizedString("homepage_theme_apply_title", "zh-CN", "应用主题");
		addLocalizedString("homepage_theme_apply_title", "zh-TW", "應用主題");
		addLocalizedString("homepage_theme_apply_title", "en", "Apply Theme");
		addLocalizedString("homepage_theme_apply_message", "zh-CN", "您是否要应用主题");
		addLocalizedString("homepage_theme_apply_message", "zh-TW", "您是否要應用主題");
		addLocalizedString("homepage_theme_apply_message", "en", "Do you want to apply the theme");
		addLocalizedString("homepage_theme_apply", "zh-CN", "应用");
		addLocalizedString("homepage_theme_apply", "zh-TW", "應用");
		addLocalizedString("homepage_theme_apply", "en", "Apply");
		addLocalizedString("homepage_theme_apply_success", "zh-CN", "主题应用成功，重启Via后生效");
		addLocalizedString("homepage_theme_apply_success", "zh-TW", "主題應用成功，重啟Via後生效");
		addLocalizedString("homepage_theme_apply_success", "en",
				"Theme applied successfully, changes effective after restart Via");
		addLocalizedString("homepage_theme_apply_failed", "zh-CN", "主题应用失败，请检查网络连接");
		addLocalizedString("homepage_theme_apply_failed", "zh-TW", "主題應用失敗，請檢查網路連接");
		addLocalizedString("homepage_theme_apply_failed", "en",
				"Theme application failed, please check network connection");
		addLocalizedString("homepage_theme_apply_error", "zh-CN", "应用主题时发生错误");
		addLocalizedString("homepage_theme_apply_error", "zh-TW", "應用主題時發生錯誤");
		addLocalizedString("homepage_theme_apply_error", "en", "Error occurred while applying theme");
		addLocalizedString("homepage_theme_edit", "zh-CN", "编辑");
		addLocalizedString("homepage_theme_edit", "zh-TW", "編輯");
		addLocalizedString("homepage_theme_edit", "en", "Edit");
		addLocalizedString("homepage_theme_editor_title", "zh-CN", "主题编辑器");
		addLocalizedString("homepage_theme_editor_title", "zh-TW", "主題編輯器");
		addLocalizedString("homepage_theme_editor_title", "en", "Theme Editor");
		addLocalizedString("theme_editor_select_file", "zh-CN", "选择编辑的文件:");
		addLocalizedString("theme_editor_select_file", "zh-TW", "選擇編輯的文件:");
		addLocalizedString("theme_editor_select_file", "en", "Select file to edit:");
		addLocalizedString("theme_editor_edit_content", "zh-CN", "编辑内容:");
		addLocalizedString("theme_editor_edit_content", "zh-TW", "編輯內容:");
		addLocalizedString("theme_editor_edit_content", "en", "Edit content:");
		addLocalizedString("theme_editor_save_success", "zh-CN", "保存成功");
		addLocalizedString("theme_editor_save_success", "zh-TW", "保存成功");
		addLocalizedString("theme_editor_save_success", "en", "Save successful");
		addLocalizedString("homepage_theme_save", "zh-CN", "保存");
		addLocalizedString("homepage_theme_save", "zh-TW", "保存");
		addLocalizedString("homepage_theme_save", "en", "Save");
		addLocalizedString("homepage_theme_save_success", "zh-CN", "保存成功");
		addLocalizedString("homepage_theme_save_success", "zh-TW", "保存成功");
		addLocalizedString("homepage_theme_save_success", "en", "Save successful");
		addLocalizedString("homepage_theme_save_error", "zh-CN", "保存失败");
		addLocalizedString("homepage_theme_save_error", "zh-TW", "保存失敗");
		addLocalizedString("homepage_theme_save_error", "en", "Save failed");
		addLocalizedString("homepage_theme_file_not_found", "zh-CN", "文件不存在");
		addLocalizedString("homepage_theme_file_not_found", "zh-TW", "文件不存在");
		addLocalizedString("homepage_theme_file_not_found", "en", "File not found");
		addLocalizedString("homepage_theme_load_error", "zh-CN", "加载错误");
		addLocalizedString("homepage_theme_load_error", "zh-TW", "加載錯誤");
		addLocalizedString("homepage_theme_load_error", "en", "Load error");
		addLocalizedString("homepage_theme_edit_file", "zh-CN", "编辑文件:");
		addLocalizedString("homepage_theme_edit_file", "zh-TW", "编辑文件:");
		addLocalizedString("homepage_theme_edit_file", "en", "Edit file:");
		addLocalizedString("homepage_theme_edit_content", "zh-CN", "编辑内容:");
		addLocalizedString("homepage_theme_edit_content", "zh-TW", "编辑内容:");
		addLocalizedString("homepage_theme_edit_content", "en", "Edit content:");
		addLocalizedString("script_repository_title", "zh-CN", "脚本仓库");
		addLocalizedString("script_repository_title", "zh-TW", "腳本倉庫");
		addLocalizedString("script_repository_title", "en", "Script Repository");
		addLocalizedString("script_repository_config", "zh-CN", "配置");
		addLocalizedString("script_repository_config", "zh-TW", "配置");
		addLocalizedString("script_repository_config", "en", "Configure");
		addLocalizedString("script_repository_hint", "zh-CN", "下载浏览器脚本插件");
		addLocalizedString("script_repository_hint", "zh-TW", "下載瀏覽器腳本插件");
		addLocalizedString("script_repository_hint", "en", "Download browser script plugins");
		addLocalizedString("script_repository_dialog_title", "zh-CN", "脚本仓库");
		addLocalizedString("script_repository_dialog_title", "zh-TW", "腳本倉庫");
		addLocalizedString("script_repository_dialog_title", "en", "Script Repository");
		addLocalizedString("script_repository_subtitle", "zh-CN", "丰富的用户脚本资源，但不保证可用");
		addLocalizedString("script_repository_subtitle", "zh-TW", "豐富的用戶腳本資源，但不保證可用");
		addLocalizedString("script_repository_subtitle", "en",
				"Rich user script resources, but availability is not guaranteed");
		addLocalizedString("scripts_loading", "zh-CN", "正在加载脚本...");
		addLocalizedString("scripts_loading", "zh-TW", "正在加載腳本...");
		addLocalizedString("scripts_loading", "en", "Loading scripts...");
		addLocalizedString("scripts_load_failed", "zh-CN", "脚本加载失败");
		addLocalizedString("scripts_load_failed", "zh-TW", "腳本加載失敗");
		addLocalizedString("scripts_load_failed", "en", "Failed to load scripts");
		addLocalizedString("script_opened_in_via", "zh-CN", "已打开脚本，现在您可以继续浏览，刷新网页即可批量安装");
		addLocalizedString("script_opened_in_via", "zh-TW", "已打開腳本，現在您可以繼續瀏覽，刷新網頁即可批量安裝");
		addLocalizedString("script_opened_in_via", "en", "Script opened in Via, refresh the page to install");
		addLocalizedString("script_search_hint", "zh-CN", "搜索脚本名称或描述...");
		addLocalizedString("script_search_hint", "zh-TW", "搜尋腳本名稱或描述...");
		addLocalizedString("script_search_hint", "en", "Search script name or description...");
		addLocalizedString("script_search_button", "zh-CN", "搜索");
		addLocalizedString("script_search_button", "zh-TW", "搜索");
		addLocalizedString("script_search_button", "en", "Search");
		addLocalizedString("script_search_no_results", "zh-CN", "未找到包含\"%s\"的脚本");
		addLocalizedString("script_search_no_results", "zh-TW", "未找到包含\"%s\"的腳本");
		addLocalizedString("script_search_no_results", "en", "No scripts found containing \"%s\"");
		addLocalizedString("script_search_no_results_toast", "zh-CN", "未找到相关脚本");
		addLocalizedString("script_search_no_results_toast", "zh-TW", "未找到相關腳本");
		addLocalizedString("script_search_no_results_toast", "en", "No related scripts found");
		addLocalizedString("script_search_results", "zh-CN", "找到 %d 个脚本");
		addLocalizedString("script_search_results", "zh-TW", "找到 %d 個腳本");
		addLocalizedString("script_search_results", "en", "Found %d scripts");
		addLocalizedString("script_show_all", "zh-CN", "显示全部 %d 个脚本");
		addLocalizedString("script_show_all", "zh-TW", "顯示全部 %d 個腳本");
		addLocalizedString("script_show_all", "en", "Showing all %d scripts");
		addLocalizedString("no_scripts_available", "zh-CN", "没有可用的脚本");
		addLocalizedString("no_scripts_available", "zh-TW", "沒有可用的腳本");
		addLocalizedString("no_scripts_available", "en", "No scripts available");
		addLocalizedString("script_total_count", "zh-CN", "共收录 %d 个脚本");
		addLocalizedString("script_total_count", "zh-TW", "共收錄 %d 個腳本");
		addLocalizedString("script_total_count", "en", "Total %d scripts");
		addLocalizedString("script_filtered_count", "zh-CN", "筛选出 %d/%d 个脚本");
		addLocalizedString("script_filtered_count", "zh-TW", "篩選出 %d/%d 個腳本");
		addLocalizedString("script_filtered_count", "en", "Filtered %d/%d scripts");
		addLocalizedString("script_loading_count", "zh-CN", "正在加载脚本...");
		addLocalizedString("script_loading_count", "zh-TW", "正在加載腳本...");
		addLocalizedString("script_loading_count", "en", "Loading scripts...");
		addLocalizedString("script_load_failed_count", "zh-CN", "加载失败");
		addLocalizedString("script_load_failed_count", "zh-TW", "加載失敗");
		addLocalizedString("script_load_failed_count", "en", "Load failed");
		addLocalizedString("ad_block_rules_title", "zh-CN", "广告走开");
		addLocalizedString("ad_block_rules_title", "zh-TW", "廣告走開");
		addLocalizedString("ad_block_rules_title", "en", "Ad Block Rules");
		addLocalizedString("ad_block_rules_config", "zh-CN", "配置");
		addLocalizedString("ad_block_rules_config", "zh-TW", "配置");
		addLocalizedString("ad_block_rules_config", "en", "Configure");
		addLocalizedString("ad_block_rules_hint", "zh-CN", "点击配置广告拦截规则");
		addLocalizedString("ad_block_rules_hint", "zh-TW", "點擊配置廣告攔截規則");
		addLocalizedString("ad_block_rules_hint", "en", "Click to configure ad blocking rules");
		addLocalizedString("ad_block_rules_dialog_title", "zh-CN", "广告拦截规则");
		addLocalizedString("ad_block_rules_dialog_title", "zh-TW", "廣告攔截規則");
		addLocalizedString("ad_block_rules_dialog_title", "en", "Ad Block Rules");
		addLocalizedString("ad_block_rules_subtitle", "zh-CN", "选择适合的广告拦截规则");
		addLocalizedString("ad_block_rules_subtitle", "zh-TW", "選擇適合的廣告攔截規則");
		addLocalizedString("ad_block_rules_subtitle", "en", "Select suitable ad blocking rules");
		addLocalizedString("rules_loading", "zh-CN", "加载规则中...");
		addLocalizedString("rules_loading", "zh-TW", "加載規則中...");
		addLocalizedString("rules_loading", "en", "Loading rules...");
		addLocalizedString("rules_load_failed", "zh-CN", "规则加载失败");
		addLocalizedString("rules_load_failed", "zh-TW", "規則加載失敗");
		addLocalizedString("rules_load_failed", "en", "Failed to load rules");
		addLocalizedString("rules_category_small", "zh-CN", "小型规则");
		addLocalizedString("rules_category_small", "zh-TW", "小型規則");
		addLocalizedString("rules_category_small", "en", "Small Rules");
		addLocalizedString("rules_category_large", "zh-CN", "大型规则");
		addLocalizedString("rules_category_large", "zh-TW", "大型規則");
		addLocalizedString("rules_category_large", "en", "Large Rules");
		addLocalizedString("rule_author", "zh-CN", "作者");
		addLocalizedString("rule_author", "zh-TW", "作者");
		addLocalizedString("rule_author", "en", "Author");
		addLocalizedString("rule_homepage", "zh-CN", "主页");
		addLocalizedString("rule_homepage", "zh-TW", "主頁");
		addLocalizedString("rule_homepage", "en", "Homepage");
		addLocalizedString("rule_channel", "zh-CN", "渠道");
		addLocalizedString("rule_channel", "zh-TW", "渠道");
		addLocalizedString("rule_channel", "en", "Channel");
		addLocalizedString("rule_link_copied", "zh-CN", "链接已复制到剪贴板");
		addLocalizedString("rule_link_copied", "zh-TW", "連結已複製到剪貼板");
		addLocalizedString("rule_link_copied", "en", "Link copied to clipboard");
		addLocalizedString("cannot_open_homepage", "zh-CN", "无法打开主页链接");
		addLocalizedString("cannot_open_homepage", "zh-TW", "無法開啟主頁連結");
		addLocalizedString("cannot_open_homepage", "en", "Cannot open homepage link");
		addLocalizedString("homepage_bg_title", "zh-CN", "资源界面美化");
		addLocalizedString("homepage_bg_title", "zh-TW", "資源界面美化");
		addLocalizedString("homepage_bg_title", "en", "Resource UI Beauty");
		addLocalizedString("homepage_bg_config", "zh-CN", "配置");
		addLocalizedString("homepage_bg_config", "zh-TW", "配置");
		addLocalizedString("homepage_bg_config", "en", "Pick");
		addLocalizedString("homepage_bg_hint", "zh-CN", "为日志/资源页设置背景图");
		addLocalizedString("homepage_bg_hint", "zh-TW", "為日誌/資源頁設定背景圖");
		addLocalizedString("homepage_bg_hint", "en", "Set background for log/resource page");
		addLocalizedString("homepage_bg_dialog_title", "zh-CN", "资源界面美化");
		addLocalizedString("homepage_bg_dialog_title", "zh-TW", "資源界面美化");
		addLocalizedString("homepage_bg_dialog_title", "en", "Resource UI Beauty");
		addLocalizedString("homepage_bg_dialog_subtitle", "zh-CN", "调整背景图与遮罩，让文字更清晰");
		addLocalizedString("homepage_bg_dialog_subtitle", "zh-TW", "調整背景圖與遮罩，讓文字更清晰");
		addLocalizedString("homepage_bg_dialog_subtitle", "en", "Adjust background & mask to keep text clear");
		addLocalizedString("homepage_bg_pick_btn", "zh-CN", "选择图片");
		addLocalizedString("homepage_bg_pick_btn", "zh-TW", "選擇圖片");
		addLocalizedString("homepage_bg_pick_btn", "en", "Select Image");
		addLocalizedString("homepage_bg_mask_alpha", "zh-CN", "遮罩透明度");
		addLocalizedString("homepage_bg_mask_alpha", "zh-TW", "遮罩透明度");
		addLocalizedString("homepage_bg_mask_alpha", "en", "Mask Opacity");
		addLocalizedString("homepage_bg_mask_color", "zh-CN", "遮罩色相");
		addLocalizedString("homepage_bg_mask_color", "zh-TW", "遮罩色相");
		addLocalizedString("homepage_bg_mask_color", "en", "Mask Hue");
		addLocalizedString("homepage_bg_mask_color_rgb", "zh-CN", "遮罩颜色（RGB）");
		addLocalizedString("homepage_bg_mask_color_rgb", "zh-TW", "遮罩顏色（RGB）");
		addLocalizedString("homepage_bg_mask_color_rgb", "en", "Mask Color (RGB)");
		addLocalizedString("homepage_bg_mask_color_confirm", "zh-CN", "确认");
		addLocalizedString("homepage_bg_mask_color_confirm", "zh-TW", "確認");
		addLocalizedString("homepage_bg_mask_color_confirm", "en", "Confirm");
		addLocalizedString("homepage_bg_mask_color_invalid", "zh-CN", "颜色格式无效，请使用#RRGGBB格式");
		addLocalizedString("homepage_bg_mask_color_invalid", "zh-TW", "顏色格式無效，請使用#RRGGBB格式");
		addLocalizedString("homepage_bg_mask_color_invalid", "en", "Invalid color format, please use #RRGGBB");
		addLocalizedString("homepage_bg_mask_color_hint", "zh-CN", "输入RGB颜色代码（如#FFFFFF表示白色）");
		addLocalizedString("homepage_bg_mask_color_hint", "zh-TW", "輸入RGB顏色代碼（如#FFFFFF表示白色）");
		addLocalizedString("homepage_bg_mask_color_hint", "en", "Enter RGB color code (e.g. #FFFFFF for white)");
		addLocalizedString("homepage_bg_set_ok", "zh-CN", "背景图已设置");
		addLocalizedString("homepage_bg_set_ok", "zh-TW", "背景圖已設定");
		addLocalizedString("homepage_bg_set_ok", "en", "Background image set");
		addLocalizedString("homepage_bg_set_fail", "zh-CN", "设置失败");
		addLocalizedString("homepage_bg_set_fail", "zh-TW", "設定失敗");
		addLocalizedString("homepage_bg_set_fail", "en", "Set failed");
		addLocalizedString("homepage_bg_saved", "zh-CN", "已成功保存");
		addLocalizedString("homepage_bg_saved", "zh-TW", "已成功保存");
		addLocalizedString("homepage_bg_saved", "en", "Saved successfully");
		addLocalizedString("block_menu_bar_title", "zh-CN", "屏蔽菜单栏");
		addLocalizedString("block_menu_bar_title", "zh-TW", "屏蔽菜單欄");
		addLocalizedString("block_menu_bar_title", "en", "Block Menu Bar");
		addLocalizedString("block_menu_bar_config", "zh-CN", "配置");
		addLocalizedString("block_menu_bar_config", "zh-TW", "配置");
		addLocalizedString("block_menu_bar_config", "en", "Configure");
		addLocalizedString("block_menu_bar_hint", "zh-CN", "屏蔽指定网址的长按菜单");
		addLocalizedString("block_menu_bar_hint", "zh-TW", "屏蔽指定網址的長按菜單");
		addLocalizedString("block_menu_bar_hint", "en", "Block long-press menu for specified URLs");
		addLocalizedString("block_menu_bar_dialog_title", "zh-CN", "屏蔽菜单栏配置");
		addLocalizedString("block_menu_bar_dialog_title", "zh-TW", "屏蔽菜單欄配置");
		addLocalizedString("block_menu_bar_dialog_title", "en", "Block Menu Bar Configuration");
		addLocalizedString("block_menu_bar_dialog_hint", "zh-CN", "输入要屏蔽菜单的网址，多个网址用逗号分隔");
		addLocalizedString("block_menu_bar_dialog_hint", "zh-TW", "輸入要屏蔽菜單的網址，多個網址用逗號分隔");
		addLocalizedString("block_menu_bar_dialog_hint", "en",
				"Enter URLs to block menu, separate multiple URLs with commas");
		addLocalizedString("block_menu_bar_input_hint", "zh-CN", "例如：example.com,test.com");
		addLocalizedString("block_menu_bar_input_hint", "zh-TW", "例如：example.com,test.com");
		addLocalizedString("block_menu_bar_input_hint", "en", "E.g.: example.com,test.com");
		addLocalizedString("block_menu_bar_saved", "zh-CN", "设置已保存");
		addLocalizedString("block_menu_bar_saved", "zh-TW", "設置已保存");
		addLocalizedString("block_menu_bar_saved", "en", "Settings saved");
		addLocalizedString("cookie_management_title", "zh-CN", "Cookie管理");
		addLocalizedString("cookie_management_title", "zh-TW", "Cookie管理");
		addLocalizedString("cookie_management_title", "en", "Cookie Management");
		addLocalizedString("cookie_management_config", "zh-CN", "管理");
		addLocalizedString("cookie_management_config", "zh-TW", "管理");
		addLocalizedString("cookie_management_config", "en", "Manage");
		addLocalizedString("cookie_management_hint", "zh-CN", "查看和管理浏览器Cookie");
		addLocalizedString("cookie_management_hint", "zh-TW", "查看和管理瀏覽器Cookie");
		addLocalizedString("cookie_management_hint", "en", "View and manage browser cookies");
		addLocalizedString("cookie_manager_dialog_title", "zh-CN", "Cookie管理器");
		addLocalizedString("cookie_manager_dialog_title", "zh-TW", "Cookie管理器");
		addLocalizedString("cookie_manager_dialog_title", "en", "Cookie Manager");
		addLocalizedString("cookie_manager_search_hint", "zh-CN", "搜索域名或Cookie名称...");
		addLocalizedString("cookie_manager_search_hint", "zh-TW", "搜尋網域或Cookie名稱...");
		addLocalizedString("cookie_manager_search_hint", "en", "Search domain or cookie name...");
		addLocalizedString("cookie_manager_search_btn", "zh-CN", "搜索");
		addLocalizedString("cookie_manager_search_btn", "zh-TW", "搜尋");
		addLocalizedString("cookie_manager_search_btn", "en", "Search");
		addLocalizedString("cookie_manager_loading", "zh-CN", "正在加载Cookie数据...");
		addLocalizedString("cookie_manager_loading", "zh-TW", "正在加載Cookie數據...");
		addLocalizedString("cookie_manager_loading", "en", "Loading cookie data...");
		addLocalizedString("cookie_manager_empty", "zh-CN", "没有找到Cookie数据");
		addLocalizedString("cookie_manager_empty", "zh-TW", "沒有找到Cookie數據");
		addLocalizedString("cookie_manager_empty", "en", "No cookie data found");
		addLocalizedString("cookie_management_refreshed", "zh-CN", "刷新成功");
		addLocalizedString("cookie_management_refreshed", "zh-TW", "刷新成功");
		addLocalizedString("cookie_management_refreshed", "en", "Refresh successful");
		addLocalizedString("cookie_search_result", "zh-CN", "找到 %d 个结果");
		addLocalizedString("cookie_search_result", "zh-TW", "找到 %d 個結果");
		addLocalizedString("cookie_search_result", "en", "Found %d results");
		addLocalizedString("cookie_manager_delete_selected", "zh-CN", "删除选中");
		addLocalizedString("cookie_manager_delete_selected", "zh-TW", "刪除選中");
		addLocalizedString("cookie_manager_delete_selected", "en", "Delete Selected");
		addLocalizedString("cookie_manager_select_all", "zh-CN", "全选");
		addLocalizedString("cookie_manager_select_all", "zh-TW", "全選");
		addLocalizedString("cookie_manager_select_all", "en", "Select All");
		addLocalizedString("cookie_manager_unselect_all", "zh-CN", "取消全选");
		addLocalizedString("cookie_manager_unselect_all", "zh-TW", "取消全選");
		addLocalizedString("cookie_manager_unselect_all", "en", "Unselect All");
		addLocalizedString("cookie_manager_selecting", "zh-CN", "正在选择所有项，请稍候...");
		addLocalizedString("cookie_manager_selecting", "zh-TW", "正在選擇所有項，請稍候...");
		addLocalizedString("cookie_manager_selecting", "en", "Selecting all items, please wait...");
		addLocalizedString("cookie_manager_unselecting", "zh-CN", "正在取消选择，请稍候...");
		addLocalizedString("cookie_manager_unselecting", "zh-TW", "正在取消選擇，請稍候...");
		addLocalizedString("cookie_manager_unselecting", "en", "Unselecting, please wait...");
		addLocalizedString("cookie_detail_dialog_title", "zh-CN", "Cookie详情");
		addLocalizedString("cookie_detail_dialog_title", "zh-TW", "Cookie詳情");
		addLocalizedString("cookie_detail_dialog_title", "en", "Cookie Details");
		addLocalizedString("cookie_field_host_key", "zh-CN", "域名:");
		addLocalizedString("cookie_field_host_key", "zh-TW", "網域:");
		addLocalizedString("cookie_field_host_key", "en", "Host:");
		addLocalizedString("cookie_field_name", "zh-CN", "名称:");
		addLocalizedString("cookie_field_name", "zh-TW", "名稱:");
		addLocalizedString("cookie_field_name", "en", "Name:");
		addLocalizedString("cookie_field_value", "zh-CN", "值:");
		addLocalizedString("cookie_field_value", "zh-TW", "值:");
		addLocalizedString("cookie_field_value", "en", "Value:");
		addLocalizedString("cookie_field_path", "zh-CN", "路径:");
		addLocalizedString("cookie_field_path", "zh-TW", "路徑:");
		addLocalizedString("cookie_field_path", "en", "Path:");
		addLocalizedString("cookie_field_creation_time", "zh-CN", "创建时间:");
		addLocalizedString("cookie_field_creation_time", "zh-TW", "建立時間:");
		addLocalizedString("cookie_field_creation_time", "en", "Creation Time:");
		addLocalizedString("cookie_field_last_access", "zh-CN", "最后访问:");
		addLocalizedString("cookie_field_last_access", "zh-TW", "最後訪問:");
		addLocalizedString("cookie_field_last_access", "en", "Last Access:");
		addLocalizedString("cookie_field_expires", "zh-CN", "过期时间:");
		addLocalizedString("cookie_field_expires", "zh-TW", "過期時間:");
		addLocalizedString("cookie_field_expires", "en", "Expires:");
		addLocalizedString("cookie_field_last_update", "zh-CN", "最后更新:");
		addLocalizedString("cookie_field_last_update", "zh-TW", "最後更新:");
		addLocalizedString("cookie_field_last_update", "en", "Last Update:");
		addLocalizedString("cookie_field_secure", "zh-CN", "安全连接(HTTPS):");
		addLocalizedString("cookie_field_secure", "zh-TW", "安全連接(HTTPS):");
		addLocalizedString("cookie_field_secure", "en", "Secure (HTTPS):");
		addLocalizedString("cookie_field_httponly", "zh-CN", "HTTP Only:");
		addLocalizedString("cookie_field_httponly", "zh-TW", "HTTP Only:");
		addLocalizedString("cookie_field_httponly", "en", "HTTP Only:");
		addLocalizedString("cookie_field_persistent", "zh-CN", "持久化:");
		addLocalizedString("cookie_field_persistent", "zh-TW", "持久化:");
		addLocalizedString("cookie_field_persistent", "en", "Persistent:");
		addLocalizedString("cookie_field_has_expires", "zh-CN", "有过期时间:");
		addLocalizedString("cookie_field_has_expires", "zh-TW", "有過期時間:");
		addLocalizedString("cookie_field_has_expires", "en", "Has Expires:");
		addLocalizedString("cookie_field_priority", "zh-CN", "优先级:");
		addLocalizedString("cookie_field_priority", "zh-TW", "優先級:");
		addLocalizedString("cookie_field_priority", "en", "Priority:");
		addLocalizedString("cookie_field_samesite", "zh-CN", "SameSite:");
		addLocalizedString("cookie_field_samesite", "zh-TW", "SameSite:");
		addLocalizedString("cookie_field_samesite", "en", "SameSite:");
		addLocalizedString("cookie_field_source_port", "zh-CN", "源端口:");
		addLocalizedString("cookie_field_source_port", "zh-TW", "來源端口:");
		addLocalizedString("cookie_field_source_port", "en", "Source Port:");
		addLocalizedString("cookie_field_source_type", "zh-CN", "源类型:");
		addLocalizedString("cookie_field_source_type", "zh-TW", "來源類型:");
		addLocalizedString("cookie_field_source_type", "en", "Source Type:");
		addLocalizedString("cookie_save_success", "zh-CN", "Cookie已保存");
		addLocalizedString("cookie_save_success", "zh-TW", "Cookie已保存");
		addLocalizedString("cookie_save_success", "en", "Cookie saved successfully");
		addLocalizedString("cookie_delete_confirm_title", "zh-CN", "确认删除");
		addLocalizedString("cookie_delete_confirm_title", "zh-TW", "確認刪除");
		addLocalizedString("cookie_delete_confirm_title", "en", "Confirm Delete");
		addLocalizedString("cookie_delete_confirm_msg", "zh-CN", "确定要删除选中的Cookie吗？此操作不可撤销。");
		addLocalizedString("cookie_delete_confirm_msg", "zh-TW", "確定要刪除選中的Cookie嗎？此操作不可撤銷。");
		addLocalizedString("cookie_delete_confirm_msg", "en",
				"Are you sure you want to delete the selected cookies? This operation cannot be undone.");
		addLocalizedString("cookie_delete_error", "zh-CN", "删除Cookie时发生错误");
		addLocalizedString("cookie_delete_error", "zh-TW", "刪除Cookie時發生錯誤");
		addLocalizedString("cookie_delete_error", "en", "Error occurred while deleting cookies");
		addLocalizedString("cookie_detail_basic_info", "zh-CN", "基本信息");
		addLocalizedString("cookie_detail_basic_info", "zh-TW", "基本資訊");
		addLocalizedString("cookie_detail_basic_info", "en", "Basic Information");
		addLocalizedString("cookie_detail_time_info", "zh-CN", "时间信息");
		addLocalizedString("cookie_detail_time_info", "zh-TW", "時間資訊");
		addLocalizedString("cookie_detail_time_info", "en", "Time Information");
		addLocalizedString("cookie_detail_security_info", "zh-CN", "安全信息");
		addLocalizedString("cookie_detail_security_info", "zh-TW", "安全資訊");
		addLocalizedString("cookie_detail_security_info", "en", "Security Information");
		addLocalizedString("cookie_detail_advanced_info", "zh-CN", "高级信息");
		addLocalizedString("cookie_detail_advanced_info", "zh-TW", "進階資訊");
		addLocalizedString("cookie_detail_advanced_info", "en", "Advanced Information");
		addLocalizedString("cookie_field_unknown", "zh-CN", "未知");
		addLocalizedString("cookie_field_unknown", "zh-TW", "未知");
		addLocalizedString("cookie_field_unknown", "en", "Unknown");
		addLocalizedString("cookie_field_session", "zh-CN", "会话Cookie");
		addLocalizedString("cookie_field_session", "zh-TW", "工作階段Cookie");
		addLocalizedString("cookie_field_session", "en", "Session Cookie");
		addLocalizedString("cookie_field_default", "zh-CN", "默认");
		addLocalizedString("cookie_field_default", "zh-TW", "預設");
		addLocalizedString("cookie_field_default", "en", "Default");
		addLocalizedString("cookie_samesite_none", "zh-CN", "未设置");
		addLocalizedString("cookie_samesite_none", "zh-TW", "未設定");
		addLocalizedString("cookie_samesite_none", "en", "Not Set");
		addLocalizedString("cookie_samesite_lax", "zh-CN", "宽松模式");
		addLocalizedString("cookie_samesite_lax", "zh-TW", "寬鬆模式");
		addLocalizedString("cookie_samesite_lax", "en", "Lax Mode");
		addLocalizedString("cookie_samesite_strict", "zh-CN", "严格模式");
		addLocalizedString("cookie_samesite_strict", "zh-TW", "嚴格模式");
		addLocalizedString("cookie_samesite_strict", "en", "Strict Mode");
		addLocalizedString("cookie_samesite_unknown", "zh-CN", "未知 (%d)");
		addLocalizedString("cookie_samesite_unknown", "zh-TW", "未知 (%d)");
		addLocalizedString("cookie_samesite_unknown", "en", "Unknown (%d)");
		addLocalizedString("cookie_source_type_none", "zh-CN", "未设置");
		addLocalizedString("cookie_source_type_none", "zh-TW", "未設定");
		addLocalizedString("cookie_source_type_none", "en", "Not Set");
		addLocalizedString("cookie_source_type_http", "zh-CN", "HTTP");
		addLocalizedString("cookie_source_type_http", "zh-TW", "HTTP");
		addLocalizedString("cookie_source_type_http", "en", "HTTP");
		addLocalizedString("cookie_source_type_https", "zh-CN", "HTTPS");
		addLocalizedString("cookie_source_type_https", "zh-TW", "HTTPS");
		addLocalizedString("cookie_source_type_https", "en", "HTTPS");
		addLocalizedString("cookie_source_type_file", "zh-CN", "文件");
		addLocalizedString("cookie_source_type_file", "zh-TW", "檔案");
		addLocalizedString("cookie_source_type_file", "en", "File");
		addLocalizedString("cookie_source_type_unknown", "zh-CN", "未知 (%d)");
		addLocalizedString("cookie_source_type_unknown", "zh-TW", "未知 (%d)");
		addLocalizedString("cookie_source_type_unknown", "en", "Unknown (%d)");
		addLocalizedString("cookie_unknown_domain", "zh-CN", "未知域名");
		addLocalizedString("cookie_unknown_domain", "zh-TW", "未知網域");
		addLocalizedString("cookie_unknown_domain", "en", "Unknown Domain");
		addLocalizedString("cookie_field_name_label", "zh-CN", "名称: ");
		addLocalizedString("cookie_field_name_label", "zh-TW", "名稱: ");
		addLocalizedString("cookie_field_name_label", "en", "Name: ");
		addLocalizedString("cookie_field_value_label", "zh-CN", "值: ");
		addLocalizedString("cookie_field_value_label", "zh-TW", "值: ");
		addLocalizedString("cookie_field_value_label", "en", "Value: ");
		addLocalizedString("cookie_no_value", "zh-CN", "无值");
		addLocalizedString("cookie_no_value", "zh-TW", "無值");
		addLocalizedString("cookie_no_value", "en", "No Value");
		addLocalizedString("cookie_manager_delete_btn", "zh-CN", "确定");
		addLocalizedString("cookie_manager_delete_btn", "zh-TW", "確定");
		addLocalizedString("cookie_manager_delete_btn", "en", "Delete");
		addLocalizedString("cookie_view_domain", "zh-CN", "域名视图");
		addLocalizedString("cookie_view_domain", "zh-TW", "網域視圖");
		addLocalizedString("cookie_view_domain", "en", "Domain View");
		addLocalizedString("cookie_view_list", "zh-CN", "列表视图");
		addLocalizedString("cookie_view_list", "zh-TW", "列表視圖");
		addLocalizedString("cookie_view_list", "en", "List View");
		addLocalizedString("cookie_view_switching", "zh-CN", "正在切换视图...");
		addLocalizedString("cookie_view_switching", "zh-TW", "正在切換視圖...");
		addLocalizedString("cookie_view_switching", "en", "Switching view...");
		addLocalizedString("cookie_domain_count_label", "zh-CN", "%d 个Cookie");
		addLocalizedString("cookie_domain_count_label", "zh-TW", "%d 個Cookie");
		addLocalizedString("cookie_domain_count_label", "en", "%d cookies");
		addLocalizedString("cookie_domain_more_label", "zh-CN", "还有 %d 个...");
		addLocalizedString("cookie_domain_more_label", "zh-TW", "還有 %d 個...");
		addLocalizedString("cookie_domain_more_label", "en", "%d more...");
		addLocalizedString("cookie_domain_delete_all", "zh-CN", "删除所有");
		addLocalizedString("cookie_domain_delete_all", "zh-TW", "刪除所有");
		addLocalizedString("cookie_domain_delete_all", "en", "Delete All");
		addLocalizedString("cookie_delete_success", "zh-CN", "已删除选中的Cookie");
		addLocalizedString("cookie_delete_success", "zh-TW", "已刪除選中的Cookie");
		addLocalizedString("cookie_delete_success", "en", "Selected cookies deleted");
		addLocalizedString("cookie_delete_no_selected", "zh-CN", "没有选中要删除的Cookie");
		addLocalizedString("cookie_delete_no_selected", "zh-TW", "沒有選中要刪除的Cookie");
		addLocalizedString("cookie_delete_no_selected", "en", "No cookies are selected for deletion");
		addLocalizedString("cookie_domain_total_count", "zh-CN", "该域名下共有 %d 个Cookie");
		addLocalizedString("cookie_domain_total_count", "zh-TW", "該網域下共有 %d 個Cookie");
		addLocalizedString("cookie_domain_total_count", "en", "This domain has %d cookies");
		addLocalizedString("cookie_domain_delete_confirm_title", "zh-CN", "删除Cookie确认");
		addLocalizedString("cookie_domain_delete_confirm_title", "zh-TW", "刪除Cookie確認");
		addLocalizedString("cookie_domain_delete_confirm_title", "en", "Delete Cookie Confirmation");
		addLocalizedString("cookie_domain_delete_confirm_msg", "zh-CN", "确定要删除域名 %s 下的所有 %d 个Cookie吗？此操作不可撤销。");
		addLocalizedString("cookie_domain_delete_confirm_msg", "zh-TW", "確定要刪除網域 %s 下的所有 %d 個Cookie嗎？此操作不可撤銷。");
		addLocalizedString("cookie_domain_delete_confirm_msg", "en",
				"Are you sure you want to delete all %d cookies from domain %s? This operation cannot be undone.");
		addLocalizedString("cookie_domain_delete_success", "zh-CN", "已删除域名 %s 下的 %d 个Cookie");
		addLocalizedString("cookie_domain_delete_success", "zh-TW", "已刪除網域 %s 下的 %d 個Cookie");
		addLocalizedString("cookie_domain_delete_success", "en", "Deleted %d cookies from domain %s");
		addLocalizedString("cookie_domain_delete_selected_confirm_msg", "zh-CN", "确定要删除选中域名下的所有Cookie吗？此操作不可撤销。");
		addLocalizedString("cookie_domain_delete_selected_confirm_msg", "zh-TW", "確定要刪除選中網域下的所有Cookie嗎？此操作不可撤銷。");
		addLocalizedString("cookie_domain_delete_selected_confirm_msg", "en",
				"Are you sure you want to delete all cookies from the selected domains? This operation cannot be undone.");
		addLocalizedString("cookie_domain_delete_selected_success", "zh-CN", "已删除 %d 个域名的共 %d 个Cookie");
		addLocalizedString("cookie_domain_delete_selected_success", "zh-TW", "已刪除 %d 個網域的共 %d 個Cookie");
		addLocalizedString("cookie_domain_delete_selected_success", "en", "Deleted %d cookies from %d domains");
		addLocalizedString("cookie_domain_search_result", "zh-CN", "找到 %d 个域名");
		addLocalizedString("cookie_domain_search_result", "zh-TW", "找到 %d 個網域");
		addLocalizedString("cookie_domain_search_result", "en", "Found %d domains");
		addLocalizedString("network_source_title", "zh-CN", "网络源");
		addLocalizedString("network_source_title", "zh-TW", "網路源");
		addLocalizedString("network_source_title", "en", "Network Source");
		addLocalizedString("network_source_hint", "zh-CN", "选择主题和脚本等资源的下载源");
		addLocalizedString("network_source_hint", "zh-TW", "選擇主題和腳本等資源的下載源");
		addLocalizedString("network_source_hint", "en",
				"Select the download source for themes, scripts and other resources");
		addLocalizedString("network_source_changed", "zh-CN", "网络源已切换至");
		addLocalizedString("network_source_changed", "zh-TW", "網路源已切換至");
		addLocalizedString("network_source_changed", "en", "Network source changed to");
		addLocalizedString("auto_update_switch", "zh-CN", "自动检查更新");
		addLocalizedString("auto_update_switch", "zh-TW", "自動檢查更新");
		addLocalizedString("auto_update_switch", "en", "Auto Check Updates");
		addLocalizedString("auto_update_hint", "zh-CN", "启动时自动检查模块更新");
		addLocalizedString("auto_update_hint", "zh-TW", "啟動時自動檢查模組更新");
		addLocalizedString("auto_update_hint", "en", "Automatically check for module updates on startup");
		addLocalizedString("developer_mode_switch", "zh-CN", "开发者模式");
		addLocalizedString("developer_mode_switch", "zh-TW", "開發者模式");
		addLocalizedString("developer_mode_switch", "en", "Developer Mode");
		addLocalizedString("developer_mode_hint", "zh-CN", "输出详细日志到文件，便于调试");
		addLocalizedString("developer_mode_hint", "zh-TW", "輸出詳細日誌到文件，便於調試");
		addLocalizedString("developer_mode_hint", "en", "Output detailed logs to file for debugging");
		addLocalizedString("new_version_found", "zh-CN", "发现新版本 %s");
		addLocalizedString("new_version_found", "zh-TW", "發現新版本 %s");
		addLocalizedString("new_version_found", "en", "New Version %s Found");
		addLocalizedString("download_now", "zh-CN", "立即下载");
		addLocalizedString("download_now", "zh-TW", "立即下載");
		addLocalizedString("download_now", "en", "Download");
		addLocalizedString("later", "zh-CN", "以后再说");
		addLocalizedString("later", "zh-TW", "以後再說");
		addLocalizedString("later", "en", "Later");
		addLocalizedString("cannot_open_download_link", "zh-CN", "无法打开下载链接");
		addLocalizedString("cannot_open_download_link", "zh-TW", "無法開啟下載連結");
		addLocalizedString("cannot_open_download_link", "en", "Cannot open download link");
		addLocalizedString("update_log_title", "zh-CN", "更新内容");
		addLocalizedString("update_log_title", "zh-TW", "更新內容");
		addLocalizedString("update_log_title", "en", "Update Log");
		addLocalizedString("module_settings_subtitle", "zh-CN", "让Via变得更好");
		addLocalizedString("module_settings_subtitle", "zh-TW", "讓Via變得更好");
		addLocalizedString("module_settings_subtitle", "en", "Make Via Better");
		addLocalizedString("themes_loading", "zh-CN", "正在加载主题...");
		addLocalizedString("themes_loading", "zh-TW", "正在加載主題...");
		addLocalizedString("themes_loading", "en", "Loading themes...");
		addLocalizedString("themes_load_failed", "zh-CN", "主题加载失败");
		addLocalizedString("themes_load_failed", "zh-TW", "主題加載失敗");
		addLocalizedString("themes_load_failed", "en", "Failed to load themes");
		addLocalizedString("check_network", "zh-CN", "请检查网络连接后重试");
		addLocalizedString("check_network", "zh-TW", "請檢查網路連接後重試");
		addLocalizedString("check_network", "en", "Please check your network connection and try again");
		addLocalizedString("user_agent_title", "zh-CN", "浏览器标识");
		addLocalizedString("user_agent_title", "zh-TW", "瀏覽器標識");
		addLocalizedString("user_agent_title", "en", "User Agent");
		addLocalizedString("user_agent_config", "zh-CN", "查看");
		addLocalizedString("user_agent_config", "zh-TW", "查看");
		addLocalizedString("user_agent_config", "en", "View");
		addLocalizedString("user_agent_hint", "zh-CN", "查看和复制各种浏览器的User-Agent");
		addLocalizedString("user_agent_hint", "zh-TW", "查看和複製各種瀏覽器的User-Agent");
		addLocalizedString("user_agent_hint", "en", "View and copy User-Agents for various browsers");
		addLocalizedString("user_agent_dialog_title", "zh-CN", "浏览器标识大全");
		addLocalizedString("user_agent_dialog_title", "zh-TW", "瀏覽器標識大全");
		addLocalizedString("user_agent_dialog_title", "en", "User Agent Collection");
		addLocalizedString("user_agent_subtitle", "zh-CN", "已根据您的设备信息个性化调整");
		addLocalizedString("user_agent_subtitle", "zh-TW", "已根據您的設備信息個性化調整");
		addLocalizedString("user_agent_subtitle", "en", "Personalized based on your device information");
		addLocalizedString("user_agent_copy", "zh-CN", "复制");
		addLocalizedString("user_agent_copy", "zh-TW", "复制");
		addLocalizedString("user_agent_copy", "en", "Copy");
		addLocalizedString("user_agent_copied", "zh-CN", "UA已复制到剪贴板");
		addLocalizedString("user_agent_copied", "zh-TW", "UA已複製到剪貼簿");
		addLocalizedString("user_agent_copied", "en", "UA copied to clipboard");
		addLocalizedString("development_toast", "zh-CN", "正在开发中，敬请期待");
		addLocalizedString("development_toast", "zh-TW", "正在開發中，敬請期待");
		addLocalizedString("development_toast", "en", "Under development, stay tuned");
		addLocalizedString("just_trust_me_switch", "zh-CN", "SSL证书绕过");
		addLocalizedString("just_trust_me_switch", "zh-TW", "SSL證書繞過");
		addLocalizedString("just_trust_me_switch", "en", "SSL Certificate Bypass");
		addLocalizedString("just_trust_me_hint", "zh-CN", "绕过SSL证书验证，用于调试和抓包");
		addLocalizedString("just_trust_me_hint", "zh-TW", "繞過SSL證書驗證，用於調試和抓包");
		addLocalizedString("just_trust_me_hint", "en",
				"Bypass SSL certificate verification for debugging and packet capture");
		addLocalizedString("version_error_title", "zh-CN", "版本错误");
		addLocalizedString("version_error_title", "zh-TW", "版本錯誤");
		addLocalizedString("version_error_title", "en", "Version Error");
		addLocalizedString("version_error_message", "zh-CN",
				"检测到您的Via版本为%s，本模块版本适用于Via 6.9.0，建议您切换Via至模块支持版本。\n继续可能会导致模块失效和Via闪退，您确定要继续吗？");
		addLocalizedString("version_error_message", "zh-TW",
				"檢測到您的Via版本為%s，本模組版本適用於Via 6.9.0，建議您切換Via至模組支援版本。\n繼續可能會導致模組失效和Via閃退，您確定要繼續嗎？");
		addLocalizedString("version_error_message", "en",
				"Detected your Via version is %s, this module version is suitable for Via 6.9.0, it is recommended to switch Via to the version supported by the module.\nContinuing may cause the module to fail and Via to crash, are you sure you want to continue?");
		addLocalizedString("version_error_dont_show_again", "zh-CN", "不再提示");
		addLocalizedString("version_error_dont_show_again", "zh-TW", "不再提示");
		addLocalizedString("version_error_dont_show_again", "en", "Don't show again");
		addLocalizedString("version_error_exit", "zh-CN", "退出");
		addLocalizedString("version_error_exit", "zh-TW", "退出");
		addLocalizedString("version_error_exit", "en", "Exit");
		addLocalizedString("version_error_continue", "zh-CN", "进入");
		addLocalizedString("version_error_continue", "zh-TW", "進入");
		addLocalizedString("version_error_continue", "en", "Continue");
		addLocalizedString("about_title", "zh-CN", "关于");
		addLocalizedString("about_title", "zh-TW", "關於");
		addLocalizedString("about_title", "en", "About");
		addLocalizedString("about_view", "zh-CN", "查看");
		addLocalizedString("about_view", "zh-TW", "查看");
		addLocalizedString("about_view", "en", "View");
		addLocalizedString("about_hint", "zh-CN", "查看模块信息和更新日志");
		addLocalizedString("about_hint", "zh-TW", "查看模組信息和更新日誌");
		addLocalizedString("about_hint", "en", "View module information and update log");
		addLocalizedString("about_subtitle", "zh-CN", "让Via变得更好");
		addLocalizedString("about_subtitle", "zh-TW", "讓Via變得更好");
		addLocalizedString("about_subtitle", "en", "Make Via Better");
		addLocalizedString("about_module_title", "zh-CN", "模块");
		addLocalizedString("about_module_title", "zh-TW", "模組");
		addLocalizedString("about_module_title", "en", "Module");
		addLocalizedString("about_version", "zh-CN", "版本");
		addLocalizedString("about_version", "zh-TW", "版本");
		addLocalizedString("about_version", "en", "Version");
		addLocalizedString("about_author", "zh-CN", "作者");
		addLocalizedString("about_author", "zh-TW", "作者");
		addLocalizedString("about_author", "en", "Author");
		addLocalizedString("about_github", "zh-CN", "GitHub");
		addLocalizedString("about_github", "zh-TW", "GitHub");
		addLocalizedString("about_github", "en", "GitHub");
		addLocalizedString("about_gitee", "zh-CN", "Gitee");
		addLocalizedString("about_gitee", "zh-TW", "Gitee");
		addLocalizedString("about_gitee", "en", "Gitee");
		addLocalizedString("about_xposed", "zh-CN", "Xposed Repo");
		addLocalizedString("about_xposed", "zh-TW", "Xposed Repo");
		addLocalizedString("about_xposed", "en", "Xposed Repo");
		addLocalizedString("about_xposed_repo", "zh-CN", "Xposed模块仓库");
		addLocalizedString("about_xposed_repo", "zh-TW", "Xposed模块仓库");
		addLocalizedString("about_xposed_repo", "en", "Xposed Module Repository");
		addLocalizedString("start_url_message", "zh-CN", "链接已打开");
		addLocalizedString("start_url_message", "zh-TW", "鏈接已打開");
		addLocalizedString("start_url_message", "en", "Link is open");
		addLocalizedString("about_update_title", "zh-CN", "更新");
		addLocalizedString("about_update_title", "zh-TW", "更新");
		addLocalizedString("about_update_title", "en", "Update");
		addLocalizedString("about_update_log0", "zh-CN", "修复了一个在移植系统上的检查错误");
		addLocalizedString("about_update_log0", "zh-TW", "修復了移植系統上的一個檢查錯誤");
		addLocalizedString("about_update_log0", "en", "Fixed a check error on the ported system");
		addLocalizedString("about_update_log1", "zh-CN", "新增屏蔽菜单栏功能，可在任意网页屏蔽长按菜单");
		addLocalizedString("about_update_log1", "zh-TW", "新增選單列屏蔽功能，可在任意網頁屏蔽長按選單");
		addLocalizedString("about_update_log1", "en",
				"Added a menu bar blocking feature, allowing long-press menus to be blocked on any webpage");
		addLocalizedString("about_update_log2", "zh-CN", "新增开发者模式，便于日志输出");
		addLocalizedString("about_update_log2", "zh-TW", "新增開發者模式，便於日誌輸出");
		addLocalizedString("about_update_log2", "en", "Added Developer Mode for easier log output");
		addLocalizedString("about_update_log3", "zh-CN", "新增莫奈时刻功能，通过改包实现莫奈取色，具体实现详见模块页面");
		addLocalizedString("about_update_log3", "zh-TW", "新增莫奈時刻功能，通過修改資源包實現莫奈取色，具體實現請參閱模組頁面");
		addLocalizedString("about_update_log3", "en",
				"New Monet Moment feature added, enabling Monet-style color extraction through package modification. For detailed implementation, refer to the module page");
		addLocalizedString("about_update_log4", "zh-CN", "优化了模块的运行逻辑，极大提高字符串获取效率");
		addLocalizedString("about_update_log4", "zh-TW", "優化了模組的執行邏輯，大幅提升字串獲取效率");
		addLocalizedString("about_update_log4", "en",
				"Optimized the module's running logic, greatly improving string retrieval efficiency");
		addLocalizedString("about_update_log5", "zh-CN", "新增多处动画和细节优化");
		addLocalizedString("about_update_log5", "zh-TW", "新增多處動畫與細節優化");
		addLocalizedString("about_update_log5", "en", "Added numerous animations and detail optimizations");
		addLocalizedString("about_thanks_title", "zh-CN", "鸣谢");
		addLocalizedString("about_thanks_title", "zh-TW", "鳴謝");
		addLocalizedString("about_thanks_title", "en", "Thanks");
		addLocalizedString("about_thanks_content", "zh-CN", "AIDE+，AndroidIDE，AOSP，MT管理器");
		addLocalizedString("about_thanks_content", "zh-TW", "AIDE+，AndroidIDE，AOSP，MT管理器");
		addLocalizedString("about_thanks_content", "en", "AIDE+，AndroidIDE，AOSP，MT Manager");
		addLocalizedString("about_thanks_others", "zh-CN", "因人数过多，不一一列举，详见模块各版面详细作者");
		addLocalizedString("about_thanks_others", "zh-TW", "因人數過多，不一一列舉，詳見模塊各版面詳細作者");
		addLocalizedString("about_thanks_others", "en",
				"Because there are too many people, we will not list them one by one. For details, please see the detailed authors in each section of the module");
		addLocalizedString("shisui_title", "zh-CN", "拾穗");
		addLocalizedString("shisui_title", "zh-TW", "拾穗");
		addLocalizedString("shisui_title", "en", "Shisui");
		addLocalizedString("shisui_hint", "zh-CN", "愿你喜爱的，从未缺席");
		addLocalizedString("shisui_hint", "zh-TW", "願你喜愛的，從未缺席");
		addLocalizedString("shisui_hint", "en", "May what you love never be absent");
		addLocalizedString("shisui_view", "zh-CN", "查看");
		addLocalizedString("shisui_view", "zh-TW", "查看");
		addLocalizedString("shisui_view", "en", "View");
		addLocalizedString("shisui_dialog_title", "zh-CN", "拾穗");
		addLocalizedString("shisui_dialog_title", "zh-TW", "拾穗");
		addLocalizedString("shisui_dialog_title", "en", "Shisui");
		addLocalizedString("shisui_dialog_subtitle", "zh-CN", "整理Via拾穗中的内容");
		addLocalizedString("shisui_dialog_subtitle", "zh-TW", "整理Via拾穗中的內容");
		addLocalizedString("shisui_dialog_subtitle", "en", "Organizing content from Via Shisui");
		addLocalizedString("shisui_loading", "zh-CN", "正在加载拾穗内容...");
		addLocalizedString("shisui_loading", "zh-TW", "正在載入拾穗內容...");
		addLocalizedString("shisui_loading", "en", "Loading Shisui content...");
		addLocalizedString("shisui_load_failed", "zh-CN", "加载失败，请检查网络连接");
		addLocalizedString("shisui_load_failed", "zh-TW", "載入失敗，請檢查網路連接");
		addLocalizedString("shisui_load_failed", "en", "Failed to load, please check your network connection");
		addLocalizedString("shisui_copy", "zh-CN", "复制");
		addLocalizedString("shisui_copy", "zh-TW", "複製");
		addLocalizedString("shisui_copy", "en", "Copy");
		addLocalizedString("shisui_copied", "zh-CN", "已复制到剪贴板");
		addLocalizedString("shisui_copied", "zh-TW", "已複製到剪貼板");
		addLocalizedString("shisui_copied", "en", "Copied to clipboard");
		addLocalizedString("shisui_source_credit", "zh-CN", "拾穗整理来自");
		addLocalizedString("shisui_source_credit", "zh-TW", "拾穗整理來自");
		addLocalizedString("shisui_source_credit", "en", "Shisui compiled by");
		addLocalizedString("url_opened", "zh-CN", "链接已打开");
		addLocalizedString("url_opened", "zh-TW", "連結已開啟");
		addLocalizedString("url_opened", "en", "Link opened");
		addLocalizedString("to_be_continued", "zh-CN", "未完待续...");
		addLocalizedString("to_be_continued", "zh-TW", "未完待續...");
		addLocalizedString("to_be_continued", "en", "To be continued...");
		addLocalizedString("cannot_open_url", "zh-CN", "无法打开链接");
		addLocalizedString("cannot_open_url", "zh-TW", "無法開啟連結");
		addLocalizedString("cannot_open_url", "en", "Cannot open link");
		addLocalizedString("download_dialog_share", "zh-CN", "分享");
		addLocalizedString("download_dialog_share", "zh-TW", "分享");
		addLocalizedString("download_dialog_share", "en", "Share");
		addLocalizedString("share_started", "zh-CN", "已启动分享");
		addLocalizedString("share_started", "zh-TW", "已啟動分享");
		addLocalizedString("share_started", "en", "Share started");
		addLocalizedString("share_failed", "zh-CN", "分享失败");
		addLocalizedString("share_failed", "zh-TW", "分享失敗");
		addLocalizedString("share_failed", "en", "Share failed");
		addLocalizedString("download_dialog_share_switch", "zh-CN", "下载分享");
		addLocalizedString("download_dialog_share_switch", "zh-TW", "下載分享");
		addLocalizedString("download_dialog_share_switch", "en", "Download Share");
		addLocalizedString("download_dialog_share_hint", "zh-CN", "在下载对话框中添加分享按钮，便于分享到其他应用");
		addLocalizedString("download_dialog_share_hint", "zh-TW", "在下載對話框中添加分享按鈕，便於分享到其他应用");
		addLocalizedString("download_dialog_share_hint", "en",
				"Add a share button in the download dialog box to facilitate sharing to other applications");
		addLocalizedString("download_dialog_share_enabled", "zh-CN", "下载分享功能已启用");
		addLocalizedString("download_dialog_share_enabled", "zh-TW", "下載分享功能已啟用");
		addLocalizedString("download_dialog_share_enabled", "en", "Download share feature enabled");
		addLocalizedString("download_dialog_share_disabled", "zh-CN", "下载分享功能已禁用");
		addLocalizedString("download_dialog_share_disabled", "zh-TW", "下載分享功能已禁用");
		addLocalizedString("download_dialog_share_disabled", "en", "Download share feature disabled");
		addLocalizedString("monet_title", "zh-CN", "莫奈时刻 (试验)");
		addLocalizedString("monet_title", "zh-TW", "莫奈時刻 (試驗)");
		addLocalizedString("monet_title", "en", "Monet Moment (Exp)");
		addLocalizedString("monet_config", "zh-CN", "配置");
		addLocalizedString("monet_config", "zh-TW", "配置");
		addLocalizedString("monet_config", "en", "Config");
		addLocalizedString("monet_hint", "zh-CN", "通过定制化修改安装包的方法实现莫奈取色");
		addLocalizedString("monet_hint", "zh-TW", "通過定制化修改安裝包的方法實現莫奈取色");
		addLocalizedString("monet_hint", "en",
				"Implementing Monet color sampling by customizing the installation package");
		addLocalizedString("monet_dialog_title", "zh-CN", "莫奈时刻");
		addLocalizedString("monet_dialog_title", "zh-TW", "莫奈時刻");
		addLocalizedString("monet_dialog_title", "en", "Monet Moment");
		addLocalizedString("monet_principle_title", "zh-CN", "实现原理");
		addLocalizedString("monet_principle_title", "zh-TW", "實現原理");
		addLocalizedString("monet_principle_title", "en", "Principle");
		addLocalizedString("monet_principle_content", "zh-CN",
				"「莫奈取色」又称动态颜色，是 Android 12 中引入的一项功能。它通过从您设置的壁纸中提取颜色，自动生成多个主题色，并允许用户选择其中一个作为系统的主要配色方案。这种功能使得系统界面能够与用户的个性化壁纸相匹配，提升了视觉体验。\n由于 Xposed 模块的特殊性，直接对 View 布局操作较为复杂，我们目前只考虑使用修改安装包的方式实现莫奈取色。我们会替换 Via 原版安装包内的 resources.arsc 和一些 xml 文件，同时对 dex 中的图片资源也进行替换，以达到莫奈取色和更换桌面图标的效果。\n模块会使用 AOSP 开源的 Android 调试签名证书 (test)，对修改完的安装包进行签名，该证书与 MT 管理器 的默认签名证书一致。您可以在下方自定义签名方案，也可以随时使用开源的相同证书无缝回退到原版Via，同时也便于下版本的莫奈更新。有必要时，您可以从 AOSP 开源仓库或本模块的开源仓库下载签名文件。\n所有的资源文件均从 Gitee 源或 Github 源线上下载，并通过 Json 文件的形式同步远程配置。处理过程中，模块会显示进度条以展示处理过程中的瞬时信息。\n当处理完成后，APK 文件的路径理论为您在 「参数配置」中所配置的路径，文件名默认为 Via_Moneted.apk ，此时，模块会主动调用系统文件管理器，使您自定义输出位置，并进行安装。");
		addLocalizedString("monet_principle_content", "zh-TW",
				"「莫奈取色」又稱動態顏色，是 Android 12 中引入的一項功能。它透過從您設定的桌布中提取顏色，自動生成多個主題色，並允許用戶選擇其中一種作為系統的主要配色方案。此功能使系統介面能與用戶的個性化桌布相匹配，提升視覺體驗。\n由於 Xposed 模組的特殊性， 直接操作 View 佈局較為複雜，目前僅考慮透過修改安裝包實現莫奈取色。我們將替換 Via 原版安裝包內的 resources.arsc 及部分 xml 檔案，同時替換 dex 中的圖片資源，以達成莫奈取色與更換桌面圖標的效果。\n本模組將採用 AOSP 開源的 Android 調試簽名證書（test）對修改後的安裝包進行簽署，該證書與 MT 管理器 的預設簽名證書完全一致。您可於下方自訂簽名方案，亦可隨時使用開源的相同證書無縫回退至原版 Via，同時便於後續版本的莫奈更新。必要時，您可從 AOSP 開源倉庫或本模組的開源倉庫下載簽名檔案。\n所有資源檔案均從Gitee或Github線上來源下載，並透過Json檔案形式同步遠端設定。處理過程中，模組將顯示進度條以呈現即時處理狀態。\n處理完成後， APK 檔案的路徑理論上為您在「參數配置」中設定的路徑，檔案名稱預設為 Via_Moneted.apk，此時模組會主動調用系統檔案管理器，讓您自定義輸出位置並進行安裝。");
		addLocalizedString("monet_principle_content", "en",
				" 「Monet Color Extraction」also known as Dynamic Colors, is a feature introduced in Android 12. It automatically generates multiple theme colors by extracting hues from your set wallpaper, allowing users to select one as the primary system color scheme. This functionality enables the system interface to harmonize with personalized wallpapers, enhancing the visual experience. \nDue to the unique nature of Xposed modules, directly manipulating View layouts is complex. We currently only consider implementing Monet Color Extraction by modifying the installation package. We will replaces resources.arsc and certain XML files within the original Via installation package, while also substituting image resources within the dex files. This achieves both Monet Color Extraction and the ability to change desktop icons. \nThe module utilizes the open-source Android debug signing certificate (test) from AOSP to sign modified installation packages. This certificate matches the default signing certificate used by MT Manager. You may customize the signing scheme below or seamlessly revert to the original Via version at any time using the same open-source certificate. This also facilitates future updates to the Monet version. When necessary, you can download the signing file from the AOSP open-source repository or this module's open-source repository.\nAll resource files are downloaded live from Gitee or GitHub sources and synchronized via JSON configuration files. During processing, the module displays a progress bar showing real-time status updates. \nUpon completion, the APK file path defaults to the location specified in 「Configuration」with the filename set as Via_Moneted.apk. The module will then automatically launch the system file manager, allowing you to customize the output location and proceed with installation.");
		addLocalizedString("monet_notes_title", "zh-CN", "注意事项");
		addLocalizedString("monet_notes_title", "zh-TW", "注意事項");
		addLocalizedString("monet_notes_title", "en", "Notes");
		addLocalizedString("monet_notes_content", "zh-CN",
				"•「莫奈取色」仅在 Android 12 及以上设备上才能够生效，运行美化版软件的设备必须满足需求\n• 强烈建议在运行该功能之前进行数据备份，特别是没有 Root 的用户，由于签名不同，会需要删除原版 Via\n• 修改包名和版本可能会导致某些未知问题，由于技术不够成熟，若确实需要修改，请您在安装后使用第三方修改器进行修改\n• 应选择合适的网络源和网络环境，保证资源下载过程不被中断\n• Via 安装包国内版来自 Via 官网，国外版来自 Google Play Store ，均通过正规途径获得\n• 修改版 Via 仅替换关于颜色和外观的资源，不进行任何其他修改\n• 该功能还在研发中，在某些设备上可能不够稳定，导致 Via 闪退，模块也可能因为权限问题，不能正确处理文件");
		addLocalizedString("monet_notes_content", "zh-TW",
				"•「莫奈取色」功能僅適用於 Android 12 及以上裝置，運行美化版軟體的設備必須滿足此需求\n• 強烈建議啟用此功能前進行資料備份，特別是未取得 Root 權限的用戶，因簽名差異需刪除原版 Via\n• 修改套件名稱與版本可能引發未知問題，因技術尚未成熟，若確需修改，建議安裝後使用第三方修改工具進行調整\n• 請選擇合適的網路來源與連線環境，確保資源下載過程不中斷\n• Via 安裝包國內版取自 Via 官網，國際版取自 Google Play Store，均透過正規管道取得\n• 修改版 Via 僅替換關於顏色和外觀的資源，不進行任何其他修改\n• 此功能仍在研發階段，部分裝置可能出現不穩定狀況導致 Via 閃退，模組亦可能因權限問題無法正確處理檔案");
		addLocalizedString("monet_notes_content", "en",
				"• 「Monet Color Selection」 is only functional on Android 12+ devices; devices running the enhanced version must meet these requirements\n• Strongly recommend backing up data before enabling this feature, especially for non-rooted users. Due to differing signatures, the original Via app must be uninstalled\n• Modifying package names or versions may cause unknown issues. As the technology is not yet mature, if modification is necessary, use a third-party modifier after installation\n• Select appropriate network sources and environments to ensure uninterrupted resource downloads\n• The domestic version of Via's installation package originates from the official Via website, while the international version comes from the Google Play Store—both obtained through legitimate channels\n• The modified version of Via only replaces resources regarding color and appearance without any other modifications\n• This feature remains under development and may exhibit instability on certain devices, potentially causing Via crashes. Modules may also fail to process files correctly due to permission issues");
		addLocalizedString("monet_config_section", "zh-CN", "参数配置");
		addLocalizedString("monet_config_section", "zh-TW", "參數配置");
		addLocalizedString("monet_config_section", "en", "Configuration");
		addLocalizedString("monet_base_ver", "zh-CN", "基础版本");
		addLocalizedString("monet_base_ver", "zh-TW", "基礎版本");
		addLocalizedString("monet_base_ver", "en", "Base Version");
		addLocalizedString("monet_base_cn", "zh-CN", "Via 国内版");
		addLocalizedString("monet_base_cn", "zh-TW", "Via 國內版");
		addLocalizedString("monet_base_cn", "en", "Via CN");
		addLocalizedString("monet_base_global", "zh-CN", "Via 国际版");
		addLocalizedString("monet_base_global", "zh-TW", "Via 國際版");
		addLocalizedString("monet_base_global", "en", "Via Global");
		addLocalizedString("monet_pkg_name", "zh-CN", "包名");
		addLocalizedString("monet_pkg_name", "zh-TW", "套件名稱");
		addLocalizedString("monet_pkg_name", "en", "Package Name");
		addLocalizedString("monet_ver_name", "zh-CN", "版本名");
		addLocalizedString("monet_ver_name", "zh-TW", "版本名");
		addLocalizedString("monet_ver_name", "en", "Version Name");
		addLocalizedString("monet_ver_code", "zh-CN", "版本号");
		addLocalizedString("monet_ver_code", "zh-TW", "版本號");
		addLocalizedString("monet_ver_code", "en", "Version Code");
		addLocalizedString("monet_sign_scheme", "zh-CN", "签名方案");
		addLocalizedString("monet_sign_scheme", "zh-TW", "簽名方案");
		addLocalizedString("monet_sign_scheme", "en", "Signature Scheme");
		addLocalizedString("monet_sign_v1v2v3", "zh-CN", "V1+V2+V3");
		addLocalizedString("monet_sign_v1v2v3", "zh-TW", "V1+V2+V3");
		addLocalizedString("monet_sign_v1v2v3", "en", "V1+V2+V3");
		addLocalizedString("monet_sign_v1v2", "zh-CN", "V1+V2");
		addLocalizedString("monet_sign_v1v2", "zh-TW", "V1+V2");
		addLocalizedString("monet_sign_v1v2", "en", "V1+V2");
		addLocalizedString("monet_sign_v1v3", "zh-CN", "V1+V3");
		addLocalizedString("monet_sign_v1v3", "zh-TW", "V1+V3");
		addLocalizedString("monet_sign_v1v3", "en", "V1+V3");
		addLocalizedString("monet_sign_v1", "zh-CN", "V1");
		addLocalizedString("monet_sign_v1", "zh-TW", "V1");
		addLocalizedString("monet_sign_v1", "en", "V1");
		addLocalizedString("monet_sign_v2v3", "zh-CN", "V2+V3 (Android 7.0+)");
		addLocalizedString("monet_sign_v2v3", "zh-TW", "V2+V3 (Android 7.0+)");
		addLocalizedString("monet_sign_v2v3", "en", "V2+V3 (Android 7.0+)");
		addLocalizedString("monet_sign_v2", "zh-CN", "V2 (Android 7.0+)");
		addLocalizedString("monet_sign_v2", "zh-TW", "V2 (Android 7.0+)");
		addLocalizedString("monet_sign_v2", "en", "V2 (Android 7.0+)");
		addLocalizedString("monet_sign_v3", "zh-CN", "V3 (Android 9.0+)");
		addLocalizedString("monet_sign_v3", "zh-TW", "V3 (Android 9.0+)");
		addLocalizedString("monet_sign_v3", "en", "V3 (Android 9.0+)");
		addLocalizedString("monet_use_icon", "zh-CN", "使用莫奈图标");
		addLocalizedString("monet_use_icon", "zh-TW", "使用莫奈圖標");
		addLocalizedString("monet_use_icon", "en", "Use Monet Icon");
		addLocalizedString("monet_make_lite", "zh-CN", "制作精简包");
		addLocalizedString("monet_make_lite", "zh-TW", "製作精簡包");
		addLocalizedString("monet_make_lite", "en", "Make Lite Package");
		addLocalizedString("monet_agreement_title", "zh-CN", "用户协议");
		addLocalizedString("monet_agreement_title", "zh-TW", "使用者協議");
		addLocalizedString("monet_agreement_title", "en", "User Agreement");
		addLocalizedString("monet_agreement_content", "zh-CN",
				"本功能旨在学习交流，不得用于非法及商业用途。模块不会添加任何恶意代码，一切修改均基于官方原始安装包。数据无价，谨慎使用。我们尊重开发者的劳动成果，并只进行必要的美化。使用本功能所造成的一切后果由使用者自行承担。");
		addLocalizedString("monet_agreement_content", "zh-TW",
				"本功能旨在學習交流，不得用於非法及商業用途。模組不會添加任何惡意程式碼，所有修改均基於官方原始安裝包。數據無價，請謹慎使用。我們尊重開發者的勞動成果，僅進行必要的優化美化。使用本功能所造成的一切後果，使用者須自行承擔。");
		addLocalizedString("monet_agreement_content", "en",
				"This feature is intended for learning and exchange purposes only and must not be used for illegal or commercial activities. The module does not inject any malicious code; all modifications are based on the official original installation package. Data is invaluable—use with caution. We respect the developer's work and only perform necessary enhancements. Users assume full responsibility for any consequences arising from the use of this feature.");
		addLocalizedString("monet_i_agree", "zh-CN", "我同意");
		addLocalizedString("monet_i_agree", "zh-TW", "我同意");
		addLocalizedString("monet_i_agree", "en", "I Agree");
		addLocalizedString("monet_continue", "zh-CN", "继续");
		addLocalizedString("monet_continue", "zh-TW", "繼續");
		addLocalizedString("monet_continue", "en", "Continue");
		addLocalizedString("monet_version_warning", "zh-CN", "检测到您的设备安卓版本可能低于 Android 12 ，不适用于此功能");
		addLocalizedString("monet_version_warning", "zh-TW", "檢測到您的設備安卓版本可能低於Android 12，不適用於此功能");
		addLocalizedString("monet_version_warning", "en",
				"It has been detected that your device's Android version may be lower than Android 12 and is not suitable for this feature");
		addLocalizedString("new_year_wish", "zh-CN", "2026新年快乐！感谢您使用BetterVia！");
		addLocalizedString("new_year_wish", "zh-TW", "2026新年快樂！感謝您使用BetterVia！");
		addLocalizedString("new_year_wish", "en", "Happy New Year 2026! Thank you for using BetterVia!");
		addLocalizedString("new_year_message", "zh-CN", "愿新的一年里：代码无bug，功能更强大！");
		addLocalizedString("new_year_message", "zh-TW", "願新的一年裡：代碼無bug，功能更強大！");
		addLocalizedString("new_year_message", "en",
				"Wish you in the new year: No bugs in code, more powerful features!");
		addLocalizedString("new_year_title", "zh-CN", "🎉 2026 新年快乐！ 🎉");
		addLocalizedString("new_year_title", "zh-TW", "🎉 2026 新年快樂！ 🎉");
		addLocalizedString("new_year_title", "en", "🎉 Happy New Year 2026! 🎉");
		addLocalizedString("new_year_wish_text", "zh-CN",
				"感谢您使用BetterVia！愿新的一年里：\n✨ 代码无bug，功能更强大 ✨\n🎁 更新更及时，体验更流畅 🎁");
		addLocalizedString("new_year_wish_text", "zh-TW",
				"感謝您使用BetterVia！願新的一年裡：\n✨ 代碼無bug，功能更強大 ✨\n🎁 更新更及時，體驗更流暢 🎁");
		addLocalizedString("new_year_wish_text", "en",
				"Thanks for using BetterVia! May the new year bring:\n✨ Bug-free code and more powerful features ✨\n🎁 Timelier updates and smoother experience 🎁");
		addLocalizedString("new_year_toast", "zh-CN", "新年快乐，感谢支持");
		addLocalizedString("new_year_toast", "zh-TW", "新年快樂，感謝支持");
		addLocalizedString("new_year_toast", "en", "Happy New Year and thanks for your support");
		addLocalizedString("new_year_fireworks_text", "zh-CN", "2026 新年快乐");
		addLocalizedString("new_year_fireworks_text", "zh-TW", "2026 新年快樂");
		addLocalizedString("new_year_fireworks_text", "en", "Happy New Year 2026");
		addLocalizedString("new_year_fireworks_subtitle", "zh-CN", "BetterVia 感谢您的支持！");
		addLocalizedString("new_year_fireworks_subtitle", "zh-TW", "BetterVia 感謝您的支持！");
		addLocalizedString("new_year_fireworks_subtitle", "en", "BetterVia thanks for your support!");
		addLocalizedString("monet_progress_title", "zh-CN", "处理中...");
		addLocalizedString("monet_progress_title", "zh-TW", "處理中...");
		addLocalizedString("monet_progress_title", "en", "Processing...");
		addLocalizedString("monet_progress_cancel", "zh-CN", "取消");
		addLocalizedString("monet_progress_cancel", "zh-TW", "取消");
		addLocalizedString("monet_progress_cancel", "en", "Cancel");
		addLocalizedString("monet_status_cleaning", "zh-CN", "正在清空临时文件夹...");
		addLocalizedString("monet_status_cleaning", "zh-TW", "正在清空臨時資料夾...");
		addLocalizedString("monet_status_cleaning", "en", "Cleaning temporary folder...");
		addLocalizedString("monet_status_loading_config", "zh-CN", "正在加载配置文件...");
		addLocalizedString("monet_status_loading_config", "zh-TW", "正在載入設定檔...");
		addLocalizedString("monet_status_loading_config", "en", "Loading configuration file...");
		addLocalizedString("monet_status_downloading_apk", "zh-CN", "正在下载资源文件 (%s/%s MB)...");
		addLocalizedString("monet_status_downloading_apk", "zh-TW", "正在下載資源文件 (%s/%s MB)...");
		addLocalizedString("monet_status_downloading_apk", "en", "Downloading resource files (%s/%s MB)...");
		addLocalizedString("monet_status_downloading_resources", "zh-CN", "正在下载资源文件...");
		addLocalizedString("monet_status_downloading_resources", "zh-TW", "正在下載資源檔案...");
		addLocalizedString("monet_status_downloading_resources", "en", "Downloading resources file...");
		addLocalizedString("monet_status_downloading_keys", "zh-CN", "正在下载签名文件...");
		addLocalizedString("monet_status_downloading_keys", "zh-TW", "正在下載簽名檔案...");
		addLocalizedString("monet_status_downloading_keys", "en", "Downloading signing files...");
		addLocalizedString("monet_status_downloading_icons", "zh-CN", "正在下载图标文件 (%s/%s)...");
		addLocalizedString("monet_status_downloading_icons", "zh-TW", "正在下載圖標檔案 (%s/%s)...");
		addLocalizedString("monet_status_downloading_icons", "en", "Downloading icon files (%s/%s)...");
		addLocalizedString("monet_status_extracting", "zh-CN", "正在解压安装包...");
		addLocalizedString("monet_status_extracting", "zh-TW", "正在解壓安裝包...");
		addLocalizedString("monet_status_extracting", "en", "Extracting APK...");
		addLocalizedString("monet_status_replacing_resources", "zh-CN", "正在替换资源文件...");
		addLocalizedString("monet_status_replacing_resources", "zh-TW", "正在替換資源檔案...");
		addLocalizedString("monet_status_replacing_resources", "en", "Replacing resources file...");
		addLocalizedString("monet_status_replacing_files", "zh-CN", "正在替换文件 (%s/%s)...");
		addLocalizedString("monet_status_replacing_files", "zh-TW", "正在替換檔案 (%s/%s)...");
		addLocalizedString("monet_status_replacing_files", "en", "Replacing files (%s/%s)...");
		addLocalizedString("monet_status_modifying_dex", "zh-CN", "正在修改dex文件...");
		addLocalizedString("monet_status_modifying_dex", "zh-TW", "正在修改dex檔案...");
		addLocalizedString("monet_status_modifying_dex", "en", "Modifying dex file...");
		addLocalizedString("monet_status_modifying_manifest", "zh-CN", "正在修改版本信息...");
		addLocalizedString("monet_status_modifying_manifest", "zh-TW", "正在修改版本資訊...");
		addLocalizedString("monet_status_modifying_manifest", "en", "Modifying version information...");
		addLocalizedString("monet_status_packing", "zh-CN", "正在打包APK...");
		addLocalizedString("monet_status_packing", "zh-TW", "正在打包APK...");
		addLocalizedString("monet_status_packing", "en", "Packing APK...");
		addLocalizedString("monet_status_signing", "zh-CN", "正在签名APK...");
		addLocalizedString("monet_status_signing", "zh-TW", "正在簽名APK...");
		addLocalizedString("monet_status_signing", "en", "Signing APK...");
		addLocalizedString("monet_status_finishing", "zh-CN", "正在完成最后的处理...");
		addLocalizedString("monet_status_finishing", "zh-TW", "正在完成最後的處理...");
		addLocalizedString("monet_status_finishing", "en", "Finishing up...");
		addLocalizedString("monet_status_completed", "zh-CN", "处理完成！");
		addLocalizedString("monet_status_completed", "zh-TW", "處理完成！");
		addLocalizedString("monet_status_completed", "en", "Processing completed!");
		addLocalizedString("monet_error_load_config", "zh-CN", "加载配置文件失败");
		addLocalizedString("monet_error_load_config", "zh-TW", "載入設定檔失敗");
		addLocalizedString("monet_error_load_config", "en", "Failed to load configuration file");
		addLocalizedString("monet_error_download", "zh-CN", "下载文件失败: %s");
		addLocalizedString("monet_error_download", "zh-TW", "下載檔案失敗: %s");
		addLocalizedString("monet_error_download", "en", "Failed to download file: %s");
		addLocalizedString("monet_error_extract", "zh-CN", "解压APK失败");
		addLocalizedString("monet_error_extract", "zh-TW", "解壓APK失敗");
		addLocalizedString("monet_error_extract", "en", "Failed to extract APK");
		addLocalizedString("monet_error_replace", "zh-CN", "替换文件失败: %s");
		addLocalizedString("monet_error_replace", "zh-TW", "替換檔案失敗: %s");
		addLocalizedString("monet_error_replace", "en", "Failed to replace file: %s");
		addLocalizedString("monet_error_modify_dex", "zh-CN", "修改dex文件失败");
		addLocalizedString("monet_error_modify_dex", "zh-TW", "修改dex檔案失敗");
		addLocalizedString("monet_error_modify_dex", "en", "Failed to modify dex file");
		addLocalizedString("monet_error_modify_manifest", "zh-CN", "修改版本信息失败");
		addLocalizedString("monet_error_modify_manifest", "zh-TW", "修改版本資訊失敗");
		addLocalizedString("monet_error_modify_manifest", "en", "Failed to modify version information");
		addLocalizedString("monet_error_pack", "zh-CN", "打包APK失败");
		addLocalizedString("monet_error_pack", "zh-TW", "打包APK失敗");
		addLocalizedString("monet_error_pack", "en", "Failed to pack APK");
		addLocalizedString("monet_error_sign", "zh-CN", "签名APK失败");
		addLocalizedString("monet_error_sign", "zh-TW", "簽名APK失敗");
		addLocalizedString("monet_error_sign", "en", "Failed to sign APK");
		addLocalizedString("monet_error_permission", "zh-CN", "权限不足，无法访问存储");
		addLocalizedString("monet_error_permission", "zh-TW", "權限不足，無法存取儲存空間");
		addLocalizedString("monet_error_permission", "en", "Permission denied, cannot access storage");
		addLocalizedString("monet_error_unknown", "zh-CN", "未知错误: %s");
		addLocalizedString("monet_error_unknown", "zh-TW", "未知錯誤: %s");
		addLocalizedString("monet_error_unknown", "en", "Unknown error: %s");
		addLocalizedString("monet_error_network", "zh-CN", "网络连接失败，请检查网络设置");
		addLocalizedString("monet_error_network", "zh-TW", "網路連線失敗，請檢查網路設定");
		addLocalizedString("monet_error_network", "en", "Network connection failed, please check network settings");
		addLocalizedString("monet_error_file_not_found", "zh-CN", "文件不存在: %s");
		addLocalizedString("monet_error_file_not_found", "zh-TW", "檔案不存在: %s");
		addLocalizedString("monet_error_file_not_found", "en", "File not found: %s");
		addLocalizedString("monet_error_invalid_json", "zh-CN", "配置文件格式错误");
		addLocalizedString("monet_error_invalid_json", "zh-TW", "設定檔格式錯誤");
		addLocalizedString("monet_error_invalid_json", "en", "Invalid configuration file format");
		addLocalizedString("monet_error_cancelled", "zh-CN", "操作已取消");
		addLocalizedString("monet_error_cancelled", "zh-TW", "操作已取消");
		addLocalizedString("monet_error_cancelled", "en", "Operation cancelled");
		addLocalizedString("monet_error_insufficient_space", "zh-CN", "存储空间不足");
		addLocalizedString("monet_error_insufficient_space", "zh-TW", "儲存空間不足");
		addLocalizedString("monet_error_insufficient_space", "en", "Insufficient storage space");
		addLocalizedString("monet_status_downloading_sign_zip", "zh-CN", "正在下载签名文件...");
		addLocalizedString("monet_status_downloading_sign_zip", "zh-TW", "正在下載簽名檔案...");
		addLocalizedString("monet_status_downloading_sign_zip", "en", "Downloading signing files...");
		addLocalizedString("monet_status_extracting_sign", "zh-CN", "正在解压签名文件...");
		addLocalizedString("monet_status_extracting_sign", "zh-TW", "正在解壓簽名檔案...");
		addLocalizedString("monet_status_extracting_sign", "en", "Extracting signing files...");
		addLocalizedString("monet_status_renaming_apk", "zh-CN", "正在重命名安装包...");
		addLocalizedString("monet_status_renaming_apk", "zh-TW", "正在重新命名安裝包...");
		addLocalizedString("monet_status_renaming_apk", "en", "Renaming APK...");
		addLocalizedString("monet_status_cleaning_temp", "zh-CN", "正在清理临时文件...");
		addLocalizedString("monet_status_cleaning_temp", "zh-TW", "正在清理臨時檔案...");
		addLocalizedString("monet_status_cleaning_temp", "en", "Cleaning temporary files...");
		addLocalizedString("monet_status_opening_apk", "zh-CN", "正在打开安装包...");
		addLocalizedString("monet_status_opening_apk", "zh-TW", "正在開啟安裝包...");
		addLocalizedString("monet_status_opening_apk", "en", "Opening APK...");
		addLocalizedString("monet_error_select_apk", "zh-CN", "无法选择合适的APK文件");
		addLocalizedString("monet_error_select_apk", "zh-TW", "無法選擇合適的APK檔案");
		addLocalizedString("monet_error_select_apk", "en", "Cannot select appropriate APK file");
		addLocalizedString("monet_error_rename", "zh-CN", "重命名文件失败");
		addLocalizedString("monet_error_rename", "zh-TW", "重新命名檔案失敗");
		addLocalizedString("monet_error_rename", "en", "Failed to rename file");
		addLocalizedString("monet_error_open_apk", "zh-CN", "无法打开安装包");
		addLocalizedString("monet_error_open_apk", "zh-TW", "無法開啟安裝包");
		addLocalizedString("monet_error_open_apk", "en", "Cannot open APK");
		addLocalizedString("monet_error_processing", "zh-CN", "正在处理中，请稍候...");
		addLocalizedString("monet_error_processing", "zh-TW", "正在處理中，請稍候...");
		addLocalizedString("monet_error_processing", "en", "Processing in progress, please wait...");
		addLocalizedString("monet_output_location", "zh-CN", "输出位置");
		addLocalizedString("monet_output_location", "zh-TW", "輸出位置");
		addLocalizedString("monet_output_location", "en", "Output Location");
		addLocalizedString("monet_output_external", "zh-CN", "应用外部目录");
		addLocalizedString("monet_output_external", "zh-TW", "應用外部目錄");
		addLocalizedString("monet_output_external", "en", "App External Directory");
		addLocalizedString("monet_output_internal", "zh-CN", "应用内部目录");
		addLocalizedString("monet_output_internal", "zh-TW", "應用內部目錄");
		addLocalizedString("monet_output_internal", "en", "App Internal Directory");
		addLocalizedString("monet_output_external_desc", "zh-CN",
				"/storage/emulated/0/Android/data/包名/files/BetterVia/temp/");
		addLocalizedString("monet_output_external_desc", "zh-TW",
				"/storage/emulated/0/Android/data/套件名稱/files/BetterVia/temp/");
		addLocalizedString("monet_output_external_desc", "en",
				"/storage/emulated/0/Android/data/package name/files/BetterVia/temp/");
		addLocalizedString("monet_output_internal_desc", "zh-CN", "/data/user/0/包名/files/BetterVia/temp/");
		addLocalizedString("monet_output_internal_desc", "zh-TW", "/data/user/0/套件名稱/files/BetterVia/temp/");
		addLocalizedString("monet_output_internal_desc", "en", "/data/user/0/package name/files/BetterVia/temp/");
		addLocalizedString("monet_save_apk", "zh-CN", "保存APK文件");
		addLocalizedString("monet_save_apk", "zh-TW", "保存APK檔案");
		addLocalizedString("monet_save_apk", "en", "Save APK File");
	}
	private void addLocalizedString(String key, String locale, String value) {
		Map<String, String> localeMap = localizedStrings.get(key);
		if (localeMap == null) {
			localeMap = new HashMap<String, String>();
			localizedStrings.put(key, localeMap);
		}
		localeMap.put(locale, value);
	}
	public String get(Context ctx, String key) {
		String locale = getLocaleCode(ctx);
		Map<String, String> localeMap = localizedStrings.get(key);
		if (localeMap == null) {
			return "";
		}
		String result = localeMap.get(locale);
		if (result == null) {
			result = localeMap.get("zh-CN");
			if (result == null) {
				for (String value : localeMap.values()) {
					if (value != null) {
						return value;
					}
				}
				return "";
			}
		}
		return result;
	}
	private String getLocaleCode(Context ctx) {
		Locale loc = getUserLocale(ctx);
		String lang = loc.getLanguage();
		String country = loc.getCountry();
		if ("zh".equals(lang)) {
			return "CN".equals(country) ? "zh-CN" : "zh-TW";
		}
		return "en";
	}
	private Locale getUserLocale(Context ctx) {
		try {
			String saved = Hook.getSavedLanguageStatic(ctx);
			if ("auto".equals(saved)) {
				Locale locale;
				if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
					locale = ctx.getResources().getConfiguration().getLocales().get(0);
				} else {
					locale = ctx.getResources().getConfiguration().locale;
				}
				return locale;
			} else if ("zh-CN".equals(saved)) {
				return Locale.SIMPLIFIED_CHINESE;
			} else if ("zh-TW".equals(saved)) {
				return Locale.TRADITIONAL_CHINESE;
			} else if ("en".equals(saved)) {
				return Locale.ENGLISH;
			}
			return Locale.getDefault();
		} catch (Exception e) {
			return Locale.getDefault();
		}
	}
}